/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.shipeasy.admin.models.CreateAlertRuleRequest
import ai.shipeasy.admin.models.CreateAlertRuleResponse
import ai.shipeasy.admin.models.DeleteAlertRuleResponse
import ai.shipeasy.admin.models.Error
import ai.shipeasy.admin.models.ListAlertRulesResponseInner
import ai.shipeasy.admin.models.ListSlackChannelsResponse
import ai.shipeasy.admin.models.UpdateAlertRuleRequest
import ai.shipeasy.admin.models.UpdateAlertRuleResponse

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.shipeasy.admin.infrastructure.ApiClient
import ai.shipeasy.admin.infrastructure.ApiResponse
import ai.shipeasy.admin.infrastructure.ClientException
import ai.shipeasy.admin.infrastructure.ClientError
import ai.shipeasy.admin.infrastructure.ServerException
import ai.shipeasy.admin.infrastructure.ServerError
import ai.shipeasy.admin.infrastructure.MultiValueMap
import ai.shipeasy.admin.infrastructure.PartConfig
import ai.shipeasy.admin.infrastructure.RequestConfig
import ai.shipeasy.admin.infrastructure.RequestMethod
import ai.shipeasy.admin.infrastructure.ResponseType
import ai.shipeasy.admin.infrastructure.Success
import ai.shipeasy.admin.infrastructure.toMultiValue

open class AlertsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://shipeasy.ai")
        }
    }

    /**
     * POST /api/admin/alert-rules
     * Create an alert rule
     * Creates a metric-threshold alert rule. &#x60;name&#x60;, &#x60;metricId&#x60;, &#x60;comparator&#x60;, and &#x60;threshold&#x60; are required; &#x60;windowHours&#x60; defaults to &#x60;24&#x60;, &#x60;severity&#x60; to &#x60;warn&#x60;, and &#x60;enabled&#x60; to &#x60;true&#x60;.  Returns &#x60;404&#x60; if &#x60;metricId&#x60; does not resolve, and &#x60;400&#x60; for a metric with no scalar form over a window (e.g. retention metrics) — the cron can&#39;t evaluate those.  **Use cases**  - **Threshold alert** — warn when an error/latency metric crosses a value over a rolling window. - **Routed alert** — set &#x60;notify&#x60; to page a specific Slack channel or on-call email instead of the project default.
     * @param createAlertRuleRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return CreateAlertRuleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createAlertRule(createAlertRuleRequest: CreateAlertRuleRequest, xProjectId: kotlin.String? = null) : CreateAlertRuleResponse = withContext(Dispatchers.IO) {
        val localVarResponse = createAlertRuleWithHttpInfo(createAlertRuleRequest = createAlertRuleRequest, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateAlertRuleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/admin/alert-rules
     * Create an alert rule
     * Creates a metric-threshold alert rule. &#x60;name&#x60;, &#x60;metricId&#x60;, &#x60;comparator&#x60;, and &#x60;threshold&#x60; are required; &#x60;windowHours&#x60; defaults to &#x60;24&#x60;, &#x60;severity&#x60; to &#x60;warn&#x60;, and &#x60;enabled&#x60; to &#x60;true&#x60;.  Returns &#x60;404&#x60; if &#x60;metricId&#x60; does not resolve, and &#x60;400&#x60; for a metric with no scalar form over a window (e.g. retention metrics) — the cron can&#39;t evaluate those.  **Use cases**  - **Threshold alert** — warn when an error/latency metric crosses a value over a rolling window. - **Routed alert** — set &#x60;notify&#x60; to page a specific Slack channel or on-call email instead of the project default.
     * @param createAlertRuleRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<CreateAlertRuleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createAlertRuleWithHttpInfo(createAlertRuleRequest: CreateAlertRuleRequest, xProjectId: kotlin.String?) : ApiResponse<CreateAlertRuleResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createAlertRuleRequestConfig(createAlertRuleRequest = createAlertRuleRequest, xProjectId = xProjectId)

        return@withContext request<CreateAlertRuleRequest, CreateAlertRuleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createAlertRule
     *
     * @param createAlertRuleRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun createAlertRuleRequestConfig(createAlertRuleRequest: CreateAlertRuleRequest, xProjectId: kotlin.String?) : RequestConfig<CreateAlertRuleRequest> {
        val localVariableBody = createAlertRuleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/admin/alert-rules",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /api/admin/alert-rules/{id}
     * Delete an alert rule
     * Deletes the alert rule. The cron stops evaluating it immediately. Use this (then create a new rule) to repoint alerting at a different metric, since &#x60;metricId&#x60; is immutable.  **Use case:** Remove an alert rule that is no longer needed, or as the first half of repointing a rule at a different metric.
     * @param id Stable opaque alert-rule id (&#x60;ar_…&#x60;) or the rule&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return DeleteAlertRuleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun deleteAlertRule(id: kotlin.String, xProjectId: kotlin.String? = null) : DeleteAlertRuleResponse = withContext(Dispatchers.IO) {
        val localVarResponse = deleteAlertRuleWithHttpInfo(id = id, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DeleteAlertRuleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /api/admin/alert-rules/{id}
     * Delete an alert rule
     * Deletes the alert rule. The cron stops evaluating it immediately. Use this (then create a new rule) to repoint alerting at a different metric, since &#x60;metricId&#x60; is immutable.  **Use case:** Remove an alert rule that is no longer needed, or as the first half of repointing a rule at a different metric.
     * @param id Stable opaque alert-rule id (&#x60;ar_…&#x60;) or the rule&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<DeleteAlertRuleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun deleteAlertRuleWithHttpInfo(id: kotlin.String, xProjectId: kotlin.String?) : ApiResponse<DeleteAlertRuleResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = deleteAlertRuleRequestConfig(id = id, xProjectId = xProjectId)

        return@withContext request<Unit, DeleteAlertRuleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteAlertRule
     *
     * @param id Stable opaque alert-rule id (&#x60;ar_…&#x60;) or the rule&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun deleteAlertRuleRequestConfig(id: kotlin.String, xProjectId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/admin/alert-rules/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/admin/alert-rules
     * List alert rules
     * Returns every alert rule in the project (not paginated). Each rule carries its bound &#x60;metricId&#x60;, the denormalised &#x60;metricName&#x60; (or &#x60;null&#x60; if the metric was removed), the comparator/threshold/window, severity, enabled flag, and delivery target.  **Use case:** Audit which metrics have alerting configured — for example to confirm an on-call threshold is set before a launch.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return kotlin.collections.List<ListAlertRulesResponseInner>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listAlertRules(xProjectId: kotlin.String? = null, q: kotlin.String? = null) : kotlin.collections.List<ListAlertRulesResponseInner> = withContext(Dispatchers.IO) {
        val localVarResponse = listAlertRulesWithHttpInfo(xProjectId = xProjectId, q = q)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ListAlertRulesResponseInner>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/admin/alert-rules
     * List alert rules
     * Returns every alert rule in the project (not paginated). Each rule carries its bound &#x60;metricId&#x60;, the denormalised &#x60;metricName&#x60; (or &#x60;null&#x60; if the metric was removed), the comparator/threshold/window, severity, enabled flag, and delivery target.  **Use case:** Audit which metrics have alerting configured — for example to confirm an on-call threshold is set before a launch.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return ApiResponse<kotlin.collections.List<ListAlertRulesResponseInner>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listAlertRulesWithHttpInfo(xProjectId: kotlin.String?, q: kotlin.String?) : ApiResponse<kotlin.collections.List<ListAlertRulesResponseInner>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listAlertRulesRequestConfig(xProjectId = xProjectId, q = q)

        return@withContext request<Unit, kotlin.collections.List<ListAlertRulesResponseInner>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAlertRules
     *
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return RequestConfig
     */
    fun listAlertRulesRequestConfig(xProjectId: kotlin.String?, q: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (q != null) {
                    put("q", listOf(q.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/admin/alert-rules",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/admin/slack/channels
     * List Slack channels
     * List the project&#39;s connected Slack channels — used to resolve an alert rule&#39;s notification target.  **Use case:** Populate a channel picker, or validate an alert rule&#39;s &#x60;--slack-channel&#x60; before saving.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ListSlackChannelsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listSlackChannels(xProjectId: kotlin.String? = null) : ListSlackChannelsResponse = withContext(Dispatchers.IO) {
        val localVarResponse = listSlackChannelsWithHttpInfo(xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListSlackChannelsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/admin/slack/channels
     * List Slack channels
     * List the project&#39;s connected Slack channels — used to resolve an alert rule&#39;s notification target.  **Use case:** Populate a channel picker, or validate an alert rule&#39;s &#x60;--slack-channel&#x60; before saving.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<ListSlackChannelsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listSlackChannelsWithHttpInfo(xProjectId: kotlin.String?) : ApiResponse<ListSlackChannelsResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listSlackChannelsRequestConfig(xProjectId = xProjectId)

        return@withContext request<Unit, ListSlackChannelsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listSlackChannels
     *
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun listSlackChannelsRequestConfig(xProjectId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/admin/slack/channels",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/admin/alert-rules/{id}
     * Update an alert rule
     * Partial update of a rule&#39;s tunable knobs. &#x60;metricId&#x60; is immutable — the metric also pins the aggregation, so a body carrying &#x60;metricId&#x60; is rejected with &#x60;409 IMMUTABLE_FIELD&#x60;; create a new rule bound to the other metric instead (rule deletion is dashboard-only).  Pass &#x60;\&quot;notify\&quot;: null&#x60; to revert the rule&#39;s delivery target back to the project default.  **Use cases**  - **Tune sensitivity** — change &#x60;threshold&#x60;/&#x60;comparator&#x60;/&#x60;windowHours&#x60; as the metric&#39;s baseline shifts. - **Pause without losing config** — &#x60;{ \&quot;enabled\&quot;: false }&#x60; instead of deleting the rule.
     * @param id Stable opaque alert-rule id (&#x60;ar_…&#x60;) or the rule&#39;s &#x60;name&#x60;.
     * @param updateAlertRuleRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return UpdateAlertRuleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateAlertRule(id: kotlin.String, updateAlertRuleRequest: UpdateAlertRuleRequest, xProjectId: kotlin.String? = null) : UpdateAlertRuleResponse = withContext(Dispatchers.IO) {
        val localVarResponse = updateAlertRuleWithHttpInfo(id = id, updateAlertRuleRequest = updateAlertRuleRequest, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as UpdateAlertRuleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/admin/alert-rules/{id}
     * Update an alert rule
     * Partial update of a rule&#39;s tunable knobs. &#x60;metricId&#x60; is immutable — the metric also pins the aggregation, so a body carrying &#x60;metricId&#x60; is rejected with &#x60;409 IMMUTABLE_FIELD&#x60;; create a new rule bound to the other metric instead (rule deletion is dashboard-only).  Pass &#x60;\&quot;notify\&quot;: null&#x60; to revert the rule&#39;s delivery target back to the project default.  **Use cases**  - **Tune sensitivity** — change &#x60;threshold&#x60;/&#x60;comparator&#x60;/&#x60;windowHours&#x60; as the metric&#39;s baseline shifts. - **Pause without losing config** — &#x60;{ \&quot;enabled\&quot;: false }&#x60; instead of deleting the rule.
     * @param id Stable opaque alert-rule id (&#x60;ar_…&#x60;) or the rule&#39;s &#x60;name&#x60;.
     * @param updateAlertRuleRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<UpdateAlertRuleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateAlertRuleWithHttpInfo(id: kotlin.String, updateAlertRuleRequest: UpdateAlertRuleRequest, xProjectId: kotlin.String?) : ApiResponse<UpdateAlertRuleResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateAlertRuleRequestConfig(id = id, updateAlertRuleRequest = updateAlertRuleRequest, xProjectId = xProjectId)

        return@withContext request<UpdateAlertRuleRequest, UpdateAlertRuleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateAlertRule
     *
     * @param id Stable opaque alert-rule id (&#x60;ar_…&#x60;) or the rule&#39;s &#x60;name&#x60;.
     * @param updateAlertRuleRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun updateAlertRuleRequestConfig(id: kotlin.String, updateAlertRuleRequest: UpdateAlertRuleRequest, xProjectId: kotlin.String?) : RequestConfig<UpdateAlertRuleRequest> {
        val localVariableBody = updateAlertRuleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/admin/alert-rules/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
