/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.shipeasy.admin.models.CreateKeyRequest
import ai.shipeasy.admin.models.CreateKeyResponse
import ai.shipeasy.admin.models.Error
import ai.shipeasy.admin.models.ListKeysResponse
import ai.shipeasy.admin.models.RevokeKeyResponse

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.shipeasy.admin.infrastructure.ApiClient
import ai.shipeasy.admin.infrastructure.ApiResponse
import ai.shipeasy.admin.infrastructure.ClientException
import ai.shipeasy.admin.infrastructure.ClientError
import ai.shipeasy.admin.infrastructure.ServerException
import ai.shipeasy.admin.infrastructure.ServerError
import ai.shipeasy.admin.infrastructure.MultiValueMap
import ai.shipeasy.admin.infrastructure.PartConfig
import ai.shipeasy.admin.infrastructure.RequestConfig
import ai.shipeasy.admin.infrastructure.RequestMethod
import ai.shipeasy.admin.infrastructure.ResponseType
import ai.shipeasy.admin.infrastructure.Success
import ai.shipeasy.admin.infrastructure.toMultiValue

open class APIKeysApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://shipeasy.ai")
        }
    }

    /**
     * POST /api/admin/keys
     * Create an API key
     * Mints a new API key and returns the plaintext token **once** — it is stored hashed and can never be retrieved again, so capture it on creation.  Only &#x60;type&#x60; is required. &#x60;env&#x60; is **required** for &#x60;server&#x60; and &#x60;client&#x60; keys (the key is bound to one environment, which is the read-env isolation boundary); for &#x60;admin&#x60; and &#x60;ops&#x60; keys &#x60;env&#x60; is ignored and the key is pinned to &#x60;prod&#x60;. Expiry is fixed for some types: &#x60;admin&#x60; keys always get a 90-day expiry and &#x60;ops&#x60; keys a short sliding window, regardless of &#x60;expiresInDays&#x60;. Only &#x60;server&#x60;/&#x60;client&#x60; keys count toward the plan key limit.  **Use cases**  - **Back-end key** — &#x60;{ \&quot;type\&quot;: \&quot;server\&quot;, \&quot;env\&quot;: \&quot;prod\&quot; }&#x60; for the production server SDK. - **Public browser key** — &#x60;{ \&quot;type\&quot;: \&quot;client\&quot;, \&quot;env\&quot;: \&quot;prod\&quot;, \&quot;name\&quot;: \&quot;marketing site\&quot; }&#x60; to embed in the browser SDK. - **Scoped, expiring key** — &#x60;{ \&quot;type\&quot;: \&quot;server\&quot;, \&quot;env\&quot;: \&quot;staging\&quot;, \&quot;scopes\&quot;: [\&quot;gates:evaluate\&quot;], \&quot;expiresInDays\&quot;: 30 }&#x60; for a time-boxed integration.
     * @param createKeyRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return CreateKeyResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createKey(createKeyRequest: CreateKeyRequest, xProjectId: kotlin.String? = null) : CreateKeyResponse = withContext(Dispatchers.IO) {
        val localVarResponse = createKeyWithHttpInfo(createKeyRequest = createKeyRequest, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateKeyResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/admin/keys
     * Create an API key
     * Mints a new API key and returns the plaintext token **once** — it is stored hashed and can never be retrieved again, so capture it on creation.  Only &#x60;type&#x60; is required. &#x60;env&#x60; is **required** for &#x60;server&#x60; and &#x60;client&#x60; keys (the key is bound to one environment, which is the read-env isolation boundary); for &#x60;admin&#x60; and &#x60;ops&#x60; keys &#x60;env&#x60; is ignored and the key is pinned to &#x60;prod&#x60;. Expiry is fixed for some types: &#x60;admin&#x60; keys always get a 90-day expiry and &#x60;ops&#x60; keys a short sliding window, regardless of &#x60;expiresInDays&#x60;. Only &#x60;server&#x60;/&#x60;client&#x60; keys count toward the plan key limit.  **Use cases**  - **Back-end key** — &#x60;{ \&quot;type\&quot;: \&quot;server\&quot;, \&quot;env\&quot;: \&quot;prod\&quot; }&#x60; for the production server SDK. - **Public browser key** — &#x60;{ \&quot;type\&quot;: \&quot;client\&quot;, \&quot;env\&quot;: \&quot;prod\&quot;, \&quot;name\&quot;: \&quot;marketing site\&quot; }&#x60; to embed in the browser SDK. - **Scoped, expiring key** — &#x60;{ \&quot;type\&quot;: \&quot;server\&quot;, \&quot;env\&quot;: \&quot;staging\&quot;, \&quot;scopes\&quot;: [\&quot;gates:evaluate\&quot;], \&quot;expiresInDays\&quot;: 30 }&#x60; for a time-boxed integration.
     * @param createKeyRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<CreateKeyResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createKeyWithHttpInfo(createKeyRequest: CreateKeyRequest, xProjectId: kotlin.String?) : ApiResponse<CreateKeyResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createKeyRequestConfig(createKeyRequest = createKeyRequest, xProjectId = xProjectId)

        return@withContext request<CreateKeyRequest, CreateKeyResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createKey
     *
     * @param createKeyRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun createKeyRequestConfig(createKeyRequest: CreateKeyRequest, xProjectId: kotlin.String?) : RequestConfig<CreateKeyRequest> {
        val localVariableBody = createKeyRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/admin/keys",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/admin/keys
     * List API keys
     * Returns a single page of the project&#39;s API keys ordered by &#x60;created_at desc, id desc&#x60;, in the standard &#x60;{ data, next_cursor }&#x60; envelope. Use the &#x60;cursor&#x60; query parameter to paginate.  Response fields are **snake_case** (&#x60;created_at&#x60;, &#x60;revoked_at&#x60;, &#x60;created_by_email&#x60;, &#x60;last4&#x60;). The raw token is never returned — only its &#x60;last4&#x60; tail, so a held key can be matched against the masked row. Revoked keys are included (with a non-null &#x60;revoked_at&#x60;).  **Use case:** Audit which keys exist for a project — surface stale or never-expiring keys, or drive a CI check that asserts no &#x60;client&#x60; key is still active in &#x60;prod&#x60; after a rotation.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param limit Page size (1–500). Defaults to 100. (optional, default to 100)
     * @param cursor Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return ListKeysResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listKeys(xProjectId: kotlin.String? = null, limit: kotlin.Int? = 100, cursor: kotlin.String? = null, q: kotlin.String? = null) : ListKeysResponse = withContext(Dispatchers.IO) {
        val localVarResponse = listKeysWithHttpInfo(xProjectId = xProjectId, limit = limit, cursor = cursor, q = q)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListKeysResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/admin/keys
     * List API keys
     * Returns a single page of the project&#39;s API keys ordered by &#x60;created_at desc, id desc&#x60;, in the standard &#x60;{ data, next_cursor }&#x60; envelope. Use the &#x60;cursor&#x60; query parameter to paginate.  Response fields are **snake_case** (&#x60;created_at&#x60;, &#x60;revoked_at&#x60;, &#x60;created_by_email&#x60;, &#x60;last4&#x60;). The raw token is never returned — only its &#x60;last4&#x60; tail, so a held key can be matched against the masked row. Revoked keys are included (with a non-null &#x60;revoked_at&#x60;).  **Use case:** Audit which keys exist for a project — surface stale or never-expiring keys, or drive a CI check that asserts no &#x60;client&#x60; key is still active in &#x60;prod&#x60; after a rotation.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param limit Page size (1–500). Defaults to 100. (optional, default to 100)
     * @param cursor Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return ApiResponse<ListKeysResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listKeysWithHttpInfo(xProjectId: kotlin.String?, limit: kotlin.Int?, cursor: kotlin.String?, q: kotlin.String?) : ApiResponse<ListKeysResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listKeysRequestConfig(xProjectId = xProjectId, limit = limit, cursor = cursor, q = q)

        return@withContext request<Unit, ListKeysResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listKeys
     *
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param limit Page size (1–500). Defaults to 100. (optional, default to 100)
     * @param cursor Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return RequestConfig
     */
    fun listKeysRequestConfig(xProjectId: kotlin.String?, limit: kotlin.Int?, cursor: kotlin.String?, q: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
                if (q != null) {
                    put("q", listOf(q.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/admin/keys",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/admin/keys/{id}/revoke
     * Revoke an API key
     * Revokes a key by id — stamps its &#x60;revoked_at&#x60; and deletes the hot-path KV entry so the token stops authenticating immediately. Takes no body.  Idempotent: revoking an already-revoked key is a no-op and returns the same &#x60;{ id, revoked: true }&#x60;. Returns &#x60;404&#x60; if no such key exists in the project.  **Use case:** Rotate a leaked or stale credential — mint the replacement, then revoke the old key.
     * @param id Stable opaque key id (UUID) returned by &#x60;create&#x60; / &#x60;list&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RevokeKeyResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun revokeKey(id: kotlin.String, xProjectId: kotlin.String? = null) : RevokeKeyResponse = withContext(Dispatchers.IO) {
        val localVarResponse = revokeKeyWithHttpInfo(id = id, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RevokeKeyResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/admin/keys/{id}/revoke
     * Revoke an API key
     * Revokes a key by id — stamps its &#x60;revoked_at&#x60; and deletes the hot-path KV entry so the token stops authenticating immediately. Takes no body.  Idempotent: revoking an already-revoked key is a no-op and returns the same &#x60;{ id, revoked: true }&#x60;. Returns &#x60;404&#x60; if no such key exists in the project.  **Use case:** Rotate a leaked or stale credential — mint the replacement, then revoke the old key.
     * @param id Stable opaque key id (UUID) returned by &#x60;create&#x60; / &#x60;list&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<RevokeKeyResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun revokeKeyWithHttpInfo(id: kotlin.String, xProjectId: kotlin.String?) : ApiResponse<RevokeKeyResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = revokeKeyRequestConfig(id = id, xProjectId = xProjectId)

        return@withContext request<Unit, RevokeKeyResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation revokeKey
     *
     * @param id Stable opaque key id (UUID) returned by &#x60;create&#x60; / &#x60;list&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun revokeKeyRequestConfig(id: kotlin.String, xProjectId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/admin/keys/{id}/revoke".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
