/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.shipeasy.admin.models.Error
import ai.shipeasy.admin.models.ErrorRecord
import ai.shipeasy.admin.models.ErrorSeriesRequest
import ai.shipeasy.admin.models.ErrorSeriesResponse
import ai.shipeasy.admin.models.FileErrorTicketResponse
import ai.shipeasy.admin.models.UpdateErrorStatusRequest

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.shipeasy.admin.infrastructure.ApiClient
import ai.shipeasy.admin.infrastructure.ApiResponse
import ai.shipeasy.admin.infrastructure.ClientException
import ai.shipeasy.admin.infrastructure.ClientError
import ai.shipeasy.admin.infrastructure.ServerException
import ai.shipeasy.admin.infrastructure.ServerError
import ai.shipeasy.admin.infrastructure.MultiValueMap
import ai.shipeasy.admin.infrastructure.PartConfig
import ai.shipeasy.admin.infrastructure.RequestConfig
import ai.shipeasy.admin.infrastructure.RequestMethod
import ai.shipeasy.admin.infrastructure.ResponseType
import ai.shipeasy.admin.infrastructure.Success
import ai.shipeasy.admin.infrastructure.toMultiValue

open class ErrorsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://shipeasy.ai")
        }
    }

    /**
     * POST /api/admin/errors/{id}/file
     * File a feedback ticket for an error
     * Files a feedback ticket (&#x60;type: \&quot;error\&quot;&#x60;) for a tracked production error — the \&quot;File an issue\&quot; action on the errors dashboard. The ticket carries the error&#39;s fingerprint as its &#x60;sourceRef&#x60; so it dedupes against, and joins back to, the tracked error. Takes no body.  Idempotent: if an open &#x60;error&#x60; ticket already tracks this fingerprint (hand- or auto-filed), that existing ticket is returned instead of creating a duplicate. Returns &#x60;404&#x60; if the error does not exist.  **Use case:** Promote a noisy tracked error into an actionable ticket in the ops queue (the same item the worker auto-files once an error crosses its occurrence threshold), so it can be triaged, assigned, and burned down via the &#x60;shipeasy-ops-work&#x60; skill.
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return FileErrorTicketResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun fileErrorTicket(id: kotlin.String, xProjectId: kotlin.String? = null) : FileErrorTicketResponse = withContext(Dispatchers.IO) {
        val localVarResponse = fileErrorTicketWithHttpInfo(id = id, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as FileErrorTicketResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/admin/errors/{id}/file
     * File a feedback ticket for an error
     * Files a feedback ticket (&#x60;type: \&quot;error\&quot;&#x60;) for a tracked production error — the \&quot;File an issue\&quot; action on the errors dashboard. The ticket carries the error&#39;s fingerprint as its &#x60;sourceRef&#x60; so it dedupes against, and joins back to, the tracked error. Takes no body.  Idempotent: if an open &#x60;error&#x60; ticket already tracks this fingerprint (hand- or auto-filed), that existing ticket is returned instead of creating a duplicate. Returns &#x60;404&#x60; if the error does not exist.  **Use case:** Promote a noisy tracked error into an actionable ticket in the ops queue (the same item the worker auto-files once an error crosses its occurrence threshold), so it can be triaged, assigned, and burned down via the &#x60;shipeasy-ops-work&#x60; skill.
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<FileErrorTicketResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun fileErrorTicketWithHttpInfo(id: kotlin.String, xProjectId: kotlin.String?) : ApiResponse<FileErrorTicketResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = fileErrorTicketRequestConfig(id = id, xProjectId = xProjectId)

        return@withContext request<Unit, FileErrorTicketResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation fileErrorTicket
     *
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun fileErrorTicketRequestConfig(id: kotlin.String, xProjectId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/admin/errors/{id}/file".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/admin/errors/{id}
     * Get a tracked error
     * Returns a single tracked error by its id, including the latest occurrence&#39;s stack, extras, and consequence. Returns &#x60;404&#x60; if no such error exists in the project.  **Use case:** Drill into one issue — fetch its full stack and &#x60;seenUrls&#x60; to investigate, or to render the detail panel behind a row in the errors list.
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ErrorRecord
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getError(id: kotlin.String, xProjectId: kotlin.String? = null) : ErrorRecord = withContext(Dispatchers.IO) {
        val localVarResponse = getErrorWithHttpInfo(id = id, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ErrorRecord
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/admin/errors/{id}
     * Get a tracked error
     * Returns a single tracked error by its id, including the latest occurrence&#39;s stack, extras, and consequence. Returns &#x60;404&#x60; if no such error exists in the project.  **Use case:** Drill into one issue — fetch its full stack and &#x60;seenUrls&#x60; to investigate, or to render the detail panel behind a row in the errors list.
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<ErrorRecord?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getErrorWithHttpInfo(id: kotlin.String, xProjectId: kotlin.String?) : ApiResponse<ErrorRecord?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getErrorRequestConfig(id = id, xProjectId = xProjectId)

        return@withContext request<Unit, ErrorRecord>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getError
     *
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun getErrorRequestConfig(id: kotlin.String, xProjectId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/admin/errors/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/admin/errors/{id}/series
     * Get an error&#39;s occurrence series
     * Returns a bucketed occurrence timeseries for one tracked error (by its fingerprint), read from the &#x60;shipeasy_errors&#x60; Analytics Engine dataset (near-real-time; ingest lag is seconds). The window bounds are epoch **seconds**; &#x60;to&#x60; must be strictly greater than &#x60;from&#x60;. The response echoes the SQL that produced the rows.  **Use case:** Render the trend sparkline / occurrence chart on the error detail panel, or pull the raw bucketed counts to alert when an issue&#39;s rate spikes.
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param errorSeriesRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ErrorSeriesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getErrorSeries(id: kotlin.String, errorSeriesRequest: ErrorSeriesRequest, xProjectId: kotlin.String? = null) : ErrorSeriesResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getErrorSeriesWithHttpInfo(id = id, errorSeriesRequest = errorSeriesRequest, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ErrorSeriesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/admin/errors/{id}/series
     * Get an error&#39;s occurrence series
     * Returns a bucketed occurrence timeseries for one tracked error (by its fingerprint), read from the &#x60;shipeasy_errors&#x60; Analytics Engine dataset (near-real-time; ingest lag is seconds). The window bounds are epoch **seconds**; &#x60;to&#x60; must be strictly greater than &#x60;from&#x60;. The response echoes the SQL that produced the rows.  **Use case:** Render the trend sparkline / occurrence chart on the error detail panel, or pull the raw bucketed counts to alert when an issue&#39;s rate spikes.
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param errorSeriesRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<ErrorSeriesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getErrorSeriesWithHttpInfo(id: kotlin.String, errorSeriesRequest: ErrorSeriesRequest, xProjectId: kotlin.String?) : ApiResponse<ErrorSeriesResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getErrorSeriesRequestConfig(id = id, errorSeriesRequest = errorSeriesRequest, xProjectId = xProjectId)

        return@withContext request<ErrorSeriesRequest, ErrorSeriesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getErrorSeries
     *
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param errorSeriesRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun getErrorSeriesRequestConfig(id: kotlin.String, errorSeriesRequest: ErrorSeriesRequest, xProjectId: kotlin.String?) : RequestConfig<ErrorSeriesRequest> {
        val localVariableBody = errorSeriesRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/admin/errors/{id}/series".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter status
     */
     enum class StatusListErrors(val value: kotlin.String) {
         @Json(name = "open") `open`("open"),
         @Json(name = "resolved") resolved("resolved"),
         @Json(name = "ignored") ignored("ignored"),
         @Json(name = "all") all("all");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /api/admin/errors
     * List tracked errors
     * Returns a single page of tracked production errors as a **bare JSON array** (no pagination envelope), ordered by &#x60;lastSeenAt desc&#x60;. Filter with &#x60;status&#x60;, free-text-search with &#x60;q&#x60;, and cap the page with &#x60;limit&#x60;.  Tracked errors are never filed by hand — an ingestion path (worker log drain / the &#x60;see()&#x60; SDK reporter) folds each occurrence into a row keyed by &#x60;fingerprint&#x60;, bumping &#x60;count&#x60; and &#x60;lastSeenAt&#x60;. This surface only reads them and (via PATCH) flips their &#x60;status&#x60;.  **Use case:** Snapshot the project&#39;s open issues for a triage dashboard, or drive a CI gate that fails the build when any &#x60;open&#x60; error of &#x60;kind: uncaught&#x60; exists in &#x60;prod&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param status Filter by triage state. &#x60;all&#x60; (the default) returns every status. (optional, default to Status.all)
     * @param q Case-insensitive substring match against &#x60;message&#x60;, &#x60;errorType&#x60;, and &#x60;subject&#x60;. (optional)
     * @param limit Maximum number of rows to return (1–500). Defaults to 200. (optional, default to 200)
     * @return kotlin.collections.List<ErrorRecord>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listErrors(xProjectId: kotlin.String? = null, status: StatusListErrors? = StatusListErrors.all, q: kotlin.String? = null, limit: kotlin.Int? = 200) : kotlin.collections.List<ErrorRecord> = withContext(Dispatchers.IO) {
        val localVarResponse = listErrorsWithHttpInfo(xProjectId = xProjectId, status = status, q = q, limit = limit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ErrorRecord>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/admin/errors
     * List tracked errors
     * Returns a single page of tracked production errors as a **bare JSON array** (no pagination envelope), ordered by &#x60;lastSeenAt desc&#x60;. Filter with &#x60;status&#x60;, free-text-search with &#x60;q&#x60;, and cap the page with &#x60;limit&#x60;.  Tracked errors are never filed by hand — an ingestion path (worker log drain / the &#x60;see()&#x60; SDK reporter) folds each occurrence into a row keyed by &#x60;fingerprint&#x60;, bumping &#x60;count&#x60; and &#x60;lastSeenAt&#x60;. This surface only reads them and (via PATCH) flips their &#x60;status&#x60;.  **Use case:** Snapshot the project&#39;s open issues for a triage dashboard, or drive a CI gate that fails the build when any &#x60;open&#x60; error of &#x60;kind: uncaught&#x60; exists in &#x60;prod&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param status Filter by triage state. &#x60;all&#x60; (the default) returns every status. (optional, default to Status.all)
     * @param q Case-insensitive substring match against &#x60;message&#x60;, &#x60;errorType&#x60;, and &#x60;subject&#x60;. (optional)
     * @param limit Maximum number of rows to return (1–500). Defaults to 200. (optional, default to 200)
     * @return ApiResponse<kotlin.collections.List<ErrorRecord>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listErrorsWithHttpInfo(xProjectId: kotlin.String?, status: StatusListErrors?, q: kotlin.String?, limit: kotlin.Int?) : ApiResponse<kotlin.collections.List<ErrorRecord>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listErrorsRequestConfig(xProjectId = xProjectId, status = status, q = q, limit = limit)

        return@withContext request<Unit, kotlin.collections.List<ErrorRecord>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listErrors
     *
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param status Filter by triage state. &#x60;all&#x60; (the default) returns every status. (optional, default to Status.all)
     * @param q Case-insensitive substring match against &#x60;message&#x60;, &#x60;errorType&#x60;, and &#x60;subject&#x60;. (optional)
     * @param limit Maximum number of rows to return (1–500). Defaults to 200. (optional, default to 200)
     * @return RequestConfig
     */
    fun listErrorsRequestConfig(xProjectId: kotlin.String?, status: StatusListErrors?, q: kotlin.String?, limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (status != null) {
                    put("status", listOf(status.value))
                }
                if (q != null) {
                    put("q", listOf(q.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/admin/errors",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/admin/errors/{id}
     * Update a tracked error&#39;s status
     * Flips the triage state of one error — the only mutation this surface allows. Valid transitions are between &#x60;open&#x60;, &#x60;resolved&#x60;, and &#x60;ignored&#x60;; the body must carry exactly &#x60;{ \&quot;status\&quot;: … }&#x60;.  A &#x60;resolved&#x60; error reopens automatically (ingestion-side) if it recurs; &#x60;ignored&#x60; is sticky until flipped back here. Returns the updated row.  **Use cases**  - **Triage** — &#x60;{ \&quot;status\&quot;: \&quot;ignored\&quot; }&#x60; to suppress a known-benign issue from the open list. - **Close out** — &#x60;{ \&quot;status\&quot;: \&quot;resolved\&quot; }&#x60; once the fix lands; it reopens on its own if the error recurs.
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param updateErrorStatusRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ErrorRecord
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateErrorStatus(id: kotlin.String, updateErrorStatusRequest: UpdateErrorStatusRequest, xProjectId: kotlin.String? = null) : ErrorRecord = withContext(Dispatchers.IO) {
        val localVarResponse = updateErrorStatusWithHttpInfo(id = id, updateErrorStatusRequest = updateErrorStatusRequest, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ErrorRecord
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/admin/errors/{id}
     * Update a tracked error&#39;s status
     * Flips the triage state of one error — the only mutation this surface allows. Valid transitions are between &#x60;open&#x60;, &#x60;resolved&#x60;, and &#x60;ignored&#x60;; the body must carry exactly &#x60;{ \&quot;status\&quot;: … }&#x60;.  A &#x60;resolved&#x60; error reopens automatically (ingestion-side) if it recurs; &#x60;ignored&#x60; is sticky until flipped back here. Returns the updated row.  **Use cases**  - **Triage** — &#x60;{ \&quot;status\&quot;: \&quot;ignored\&quot; }&#x60; to suppress a known-benign issue from the open list. - **Close out** — &#x60;{ \&quot;status\&quot;: \&quot;resolved\&quot; }&#x60; once the fix lands; it reopens on its own if the error recurs.
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param updateErrorStatusRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<ErrorRecord?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateErrorStatusWithHttpInfo(id: kotlin.String, updateErrorStatusRequest: UpdateErrorStatusRequest, xProjectId: kotlin.String?) : ApiResponse<ErrorRecord?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateErrorStatusRequestConfig(id = id, updateErrorStatusRequest = updateErrorStatusRequest, xProjectId = xProjectId)

        return@withContext request<UpdateErrorStatusRequest, ErrorRecord>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateErrorStatus
     *
     * @param id Stable opaque error id (&#x60;err_…&#x60;).
     * @param updateErrorStatusRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun updateErrorStatusRequestConfig(id: kotlin.String, updateErrorStatusRequest: UpdateErrorStatusRequest, xProjectId: kotlin.String?) : RequestConfig<UpdateErrorStatusRequest> {
        val localVariableBody = updateErrorStatusRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/admin/errors/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
