/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.shipeasy.admin.models.CreateGateRequest
import ai.shipeasy.admin.models.CreateGateResponse
import ai.shipeasy.admin.models.DeleteGateResponse
import ai.shipeasy.admin.models.DisableGateResponse
import ai.shipeasy.admin.models.EnableGateResponse
import ai.shipeasy.admin.models.Error
import ai.shipeasy.admin.models.ListGatesResponse
import ai.shipeasy.admin.models.UpdateGateRequest
import ai.shipeasy.admin.models.UpdateGateResponse

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.shipeasy.admin.infrastructure.ApiClient
import ai.shipeasy.admin.infrastructure.ApiResponse
import ai.shipeasy.admin.infrastructure.ClientException
import ai.shipeasy.admin.infrastructure.ClientError
import ai.shipeasy.admin.infrastructure.ServerException
import ai.shipeasy.admin.infrastructure.ServerError
import ai.shipeasy.admin.infrastructure.MultiValueMap
import ai.shipeasy.admin.infrastructure.PartConfig
import ai.shipeasy.admin.infrastructure.RequestConfig
import ai.shipeasy.admin.infrastructure.RequestMethod
import ai.shipeasy.admin.infrastructure.ResponseType
import ai.shipeasy.admin.infrastructure.Success
import ai.shipeasy.admin.infrastructure.toMultiValue

open class FlagsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://shipeasy.ai")
        }
    }

    /**
     * POST /api/admin/gates
     * Create a feature gate
     * Creates a new gate. Default &#x60;enabled: true&#x60; at the supplied &#x60;rollout_pct&#x60; (&#x60;0&#x60; &#x3D; fully dark).  Only &#x60;name&#x60; is required. Request fields use snake_case (&#x60;owner_email&#x60;); the GET response returns camelCase (&#x60;ownerEmail&#x60;, &#x60;groupName&#x60;).  Returns &#x60;409&#x60; if &#x60;name&#x60; already exists in the project (case-sensitive).  **Use cases**  - **Dark create + ramp later** — &#x60;{ \&quot;name\&quot;: \&quot;checkout_v2\&quot; }&#x60; at 0% rollout. Ramp via PATCH after deploy validation. - **Targeted rollout** — supply &#x60;rules&#x60; to gate the caller (e.g. only &#x60;plan &#x3D; pro&#x60; users) plus a &#x60;rollout_pct&#x60; to bucket within that audience. - **Gatekeeper stack** — supply &#x60;stack&#x60; instead of &#x60;rules&#x60;/&#x60;rollout_pct&#x60; for &#x60;internal ∪ beta ∪ public&#x60; fall-through. Stack entries evaluated top-to-bottom; first match wins. - **Dashboard metadata** — populate &#x60;title&#x60;, &#x60;description&#x60;, &#x60;folder&#x60;, &#x60;group&#x60;, &#x60;owner_email&#x60; so the admin UI is self-documenting from day one. - **Disabled on create** — pre-provision with &#x60;enabled: false&#x60; for a future launch; flip on with &#x60;POST /{id}/enable&#x60; at go-live.
     * @param createGateRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return CreateGateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createGate(createGateRequest: CreateGateRequest, xProjectId: kotlin.String? = null) : CreateGateResponse = withContext(Dispatchers.IO) {
        val localVarResponse = createGateWithHttpInfo(createGateRequest = createGateRequest, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateGateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/admin/gates
     * Create a feature gate
     * Creates a new gate. Default &#x60;enabled: true&#x60; at the supplied &#x60;rollout_pct&#x60; (&#x60;0&#x60; &#x3D; fully dark).  Only &#x60;name&#x60; is required. Request fields use snake_case (&#x60;owner_email&#x60;); the GET response returns camelCase (&#x60;ownerEmail&#x60;, &#x60;groupName&#x60;).  Returns &#x60;409&#x60; if &#x60;name&#x60; already exists in the project (case-sensitive).  **Use cases**  - **Dark create + ramp later** — &#x60;{ \&quot;name\&quot;: \&quot;checkout_v2\&quot; }&#x60; at 0% rollout. Ramp via PATCH after deploy validation. - **Targeted rollout** — supply &#x60;rules&#x60; to gate the caller (e.g. only &#x60;plan &#x3D; pro&#x60; users) plus a &#x60;rollout_pct&#x60; to bucket within that audience. - **Gatekeeper stack** — supply &#x60;stack&#x60; instead of &#x60;rules&#x60;/&#x60;rollout_pct&#x60; for &#x60;internal ∪ beta ∪ public&#x60; fall-through. Stack entries evaluated top-to-bottom; first match wins. - **Dashboard metadata** — populate &#x60;title&#x60;, &#x60;description&#x60;, &#x60;folder&#x60;, &#x60;group&#x60;, &#x60;owner_email&#x60; so the admin UI is self-documenting from day one. - **Disabled on create** — pre-provision with &#x60;enabled: false&#x60; for a future launch; flip on with &#x60;POST /{id}/enable&#x60; at go-live.
     * @param createGateRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<CreateGateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createGateWithHttpInfo(createGateRequest: CreateGateRequest, xProjectId: kotlin.String?) : ApiResponse<CreateGateResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createGateRequestConfig(createGateRequest = createGateRequest, xProjectId = xProjectId)

        return@withContext request<CreateGateRequest, CreateGateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createGate
     *
     * @param createGateRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun createGateRequestConfig(createGateRequest: CreateGateRequest, xProjectId: kotlin.String?) : RequestConfig<CreateGateRequest> {
        val localVariableBody = createGateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/admin/gates",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /api/admin/gates/{id}
     * Delete a feature gate
     * Soft-deletes the gate. Returns 409 if the gate is still referenced by a running experiment as a targeting gate — stop the experiment first.  **Use case:** Tear down a gate after a feature has fully shipped and the rollout flag is no longer needed.
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return DeleteGateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun deleteGate(id: kotlin.String, xProjectId: kotlin.String? = null) : DeleteGateResponse = withContext(Dispatchers.IO) {
        val localVarResponse = deleteGateWithHttpInfo(id = id, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DeleteGateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /api/admin/gates/{id}
     * Delete a feature gate
     * Soft-deletes the gate. Returns 409 if the gate is still referenced by a running experiment as a targeting gate — stop the experiment first.  **Use case:** Tear down a gate after a feature has fully shipped and the rollout flag is no longer needed.
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<DeleteGateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun deleteGateWithHttpInfo(id: kotlin.String, xProjectId: kotlin.String?) : ApiResponse<DeleteGateResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = deleteGateRequestConfig(id = id, xProjectId = xProjectId)

        return@withContext request<Unit, DeleteGateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteGate
     *
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun deleteGateRequestConfig(id: kotlin.String, xProjectId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/admin/gates/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/admin/gates/{id}/disable
     * Disable a gate
     * Sets &#x60;enabled: false&#x60; so the gate evaluates to &#x60;false&#x60; for every caller, regardless of &#x60;rollout_pct&#x60; or &#x60;rules&#x60;. Use as a quick kill switch.  **Use case:** Flip a gate off in production without redeploying — the canonical kill-switch flow.
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return DisableGateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun disableGate(id: kotlin.String, xProjectId: kotlin.String? = null) : DisableGateResponse = withContext(Dispatchers.IO) {
        val localVarResponse = disableGateWithHttpInfo(id = id, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DisableGateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/admin/gates/{id}/disable
     * Disable a gate
     * Sets &#x60;enabled: false&#x60; so the gate evaluates to &#x60;false&#x60; for every caller, regardless of &#x60;rollout_pct&#x60; or &#x60;rules&#x60;. Use as a quick kill switch.  **Use case:** Flip a gate off in production without redeploying — the canonical kill-switch flow.
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<DisableGateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun disableGateWithHttpInfo(id: kotlin.String, xProjectId: kotlin.String?) : ApiResponse<DisableGateResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = disableGateRequestConfig(id = id, xProjectId = xProjectId)

        return@withContext request<Unit, DisableGateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disableGate
     *
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun disableGateRequestConfig(id: kotlin.String, xProjectId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/admin/gates/{id}/disable".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/admin/gates/{id}/enable
     * Enable a gate
     * Sets &#x60;enabled: true&#x60;. The current &#x60;rollout_pct&#x60; is preserved.  **Use case:** Re-enable a previously disabled gate without re-issuing a full update.
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return EnableGateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun enableGate(id: kotlin.String, xProjectId: kotlin.String? = null) : EnableGateResponse = withContext(Dispatchers.IO) {
        val localVarResponse = enableGateWithHttpInfo(id = id, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EnableGateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/admin/gates/{id}/enable
     * Enable a gate
     * Sets &#x60;enabled: true&#x60;. The current &#x60;rollout_pct&#x60; is preserved.  **Use case:** Re-enable a previously disabled gate without re-issuing a full update.
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<EnableGateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun enableGateWithHttpInfo(id: kotlin.String, xProjectId: kotlin.String?) : ApiResponse<EnableGateResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = enableGateRequestConfig(id = id, xProjectId = xProjectId)

        return@withContext request<Unit, EnableGateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation enableGate
     *
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun enableGateRequestConfig(id: kotlin.String, xProjectId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/admin/gates/{id}/enable".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/admin/gates
     * List feature gates
     * Returns a single page of gates ordered by &#x60;updated_at desc, id desc&#x60;. Use the &#x60;cursor&#x60; query parameter to paginate.  **Use case:** Snapshot every gate in the project — for example to render an admin overview or to drive a CI check that asserts no gate is left at 100% in staging.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param limit Page size (1–500). Defaults to 100. (optional, default to 100)
     * @param cursor Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return ListGatesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listGates(xProjectId: kotlin.String? = null, limit: kotlin.Int? = 100, cursor: kotlin.String? = null, q: kotlin.String? = null) : ListGatesResponse = withContext(Dispatchers.IO) {
        val localVarResponse = listGatesWithHttpInfo(xProjectId = xProjectId, limit = limit, cursor = cursor, q = q)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListGatesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/admin/gates
     * List feature gates
     * Returns a single page of gates ordered by &#x60;updated_at desc, id desc&#x60;. Use the &#x60;cursor&#x60; query parameter to paginate.  **Use case:** Snapshot every gate in the project — for example to render an admin overview or to drive a CI check that asserts no gate is left at 100% in staging.
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param limit Page size (1–500). Defaults to 100. (optional, default to 100)
     * @param cursor Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return ApiResponse<ListGatesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listGatesWithHttpInfo(xProjectId: kotlin.String?, limit: kotlin.Int?, cursor: kotlin.String?, q: kotlin.String?) : ApiResponse<ListGatesResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listGatesRequestConfig(xProjectId = xProjectId, limit = limit, cursor = cursor, q = q)

        return@withContext request<Unit, ListGatesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listGates
     *
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @param limit Page size (1–500). Defaults to 100. (optional, default to 100)
     * @param cursor Opaque cursor returned in the previous page&#39;s &#x60;next_cursor&#x60;. Omit for the first page. (optional)
     * @param q Case-insensitive substring filter across the resource&#39;s human-readable text columns (e.g. &#x60;name&#x60;, &#x60;title&#x60;, &#x60;description&#x60;). OR-matched across those columns; omit to return everything. (optional)
     * @return RequestConfig
     */
    fun listGatesRequestConfig(xProjectId: kotlin.String?, limit: kotlin.Int?, cursor: kotlin.String?, q: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
                if (q != null) {
                    put("q", listOf(q.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/admin/gates",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/admin/gates/{id}
     * Update a feature gate
     * Partial update — only supplied fields change. Array fields (&#x60;rules&#x60;, &#x60;stack&#x60;) **replace** wholesale; there is no merge or append.  &#x60;name&#x60; and the gate id are immutable. The response carries only &#x60;{ id }&#x60; — re-fetch via &#x60;GET /api/admin/gates&#x60; for the new row.  **Use cases**  - **Ramp rollout** — &#x60;{ \&quot;rollout_pct\&quot;: 5000 }&#x60; for 50%. Basis points (0–10000); &#x60;100&#x60; &#x3D; 1%. - **Kill switch** — &#x60;{ \&quot;enabled\&quot;: false }&#x60;. Forces evaluation to &#x60;false&#x60; for every caller regardless of rules/rollout. Re-enable with &#x60;POST /{id}/enable&#x60; or &#x60;{ \&quot;enabled\&quot;: true }&#x60;. - **Modify a rule&#39;s &#x60;in&#x60; set** — send the full new &#x60;rules&#x60; array. To add &#x60;&#39;GB&#39;&#x60; to &#x60;[&#39;US&#39;,&#39;CA&#39;]&#x60;: &#x60;{ \&quot;rules\&quot;: [{ \&quot;attr\&quot;: \&quot;country\&quot;, \&quot;op\&quot;: \&quot;in\&quot;, \&quot;value\&quot;: [\&quot;US\&quot;,\&quot;CA\&quot;,\&quot;GB\&quot;] }] }&#x60;. No per-rule patch endpoint. - **Add targeting from scratch** — &#x60;{ \&quot;rules\&quot;: [{ \&quot;attr\&quot;: \&quot;email\&quot;, \&quot;op\&quot;: \&quot;regex\&quot;, \&quot;value\&quot;: \&quot;@acme\\\\.com$\&quot; }] }&#x60;. - **Switch to gatekeeper stack** — send a non-null &#x60;stack&#x60;. To revert to flat eval, send &#x60;{ \&quot;stack\&quot;: null }&#x60;. - **Update metadata** — any subset of &#x60;title&#x60;, &#x60;description&#x60;, &#x60;folder&#x60;, &#x60;group&#x60;, &#x60;owner_email&#x60;.
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param updateGateRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return UpdateGateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateGate(id: kotlin.String, updateGateRequest: UpdateGateRequest, xProjectId: kotlin.String? = null) : UpdateGateResponse = withContext(Dispatchers.IO) {
        val localVarResponse = updateGateWithHttpInfo(id = id, updateGateRequest = updateGateRequest, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as UpdateGateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/admin/gates/{id}
     * Update a feature gate
     * Partial update — only supplied fields change. Array fields (&#x60;rules&#x60;, &#x60;stack&#x60;) **replace** wholesale; there is no merge or append.  &#x60;name&#x60; and the gate id are immutable. The response carries only &#x60;{ id }&#x60; — re-fetch via &#x60;GET /api/admin/gates&#x60; for the new row.  **Use cases**  - **Ramp rollout** — &#x60;{ \&quot;rollout_pct\&quot;: 5000 }&#x60; for 50%. Basis points (0–10000); &#x60;100&#x60; &#x3D; 1%. - **Kill switch** — &#x60;{ \&quot;enabled\&quot;: false }&#x60;. Forces evaluation to &#x60;false&#x60; for every caller regardless of rules/rollout. Re-enable with &#x60;POST /{id}/enable&#x60; or &#x60;{ \&quot;enabled\&quot;: true }&#x60;. - **Modify a rule&#39;s &#x60;in&#x60; set** — send the full new &#x60;rules&#x60; array. To add &#x60;&#39;GB&#39;&#x60; to &#x60;[&#39;US&#39;,&#39;CA&#39;]&#x60;: &#x60;{ \&quot;rules\&quot;: [{ \&quot;attr\&quot;: \&quot;country\&quot;, \&quot;op\&quot;: \&quot;in\&quot;, \&quot;value\&quot;: [\&quot;US\&quot;,\&quot;CA\&quot;,\&quot;GB\&quot;] }] }&#x60;. No per-rule patch endpoint. - **Add targeting from scratch** — &#x60;{ \&quot;rules\&quot;: [{ \&quot;attr\&quot;: \&quot;email\&quot;, \&quot;op\&quot;: \&quot;regex\&quot;, \&quot;value\&quot;: \&quot;@acme\\\\.com$\&quot; }] }&#x60;. - **Switch to gatekeeper stack** — send a non-null &#x60;stack&#x60;. To revert to flat eval, send &#x60;{ \&quot;stack\&quot;: null }&#x60;. - **Update metadata** — any subset of &#x60;title&#x60;, &#x60;description&#x60;, &#x60;folder&#x60;, &#x60;group&#x60;, &#x60;owner_email&#x60;.
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param updateGateRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<UpdateGateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateGateWithHttpInfo(id: kotlin.String, updateGateRequest: UpdateGateRequest, xProjectId: kotlin.String?) : ApiResponse<UpdateGateResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateGateRequestConfig(id = id, updateGateRequest = updateGateRequest, xProjectId = xProjectId)

        return@withContext request<UpdateGateRequest, UpdateGateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateGate
     *
     * @param id Stable opaque gate id (&#x60;gat_…&#x60;) or the gate&#39;s &#x60;name&#x60;.
     * @param updateGateRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun updateGateRequestConfig(id: kotlin.String, updateGateRequest: UpdateGateRequest, xProjectId: kotlin.String?) : RequestConfig<UpdateGateRequest> {
        val localVariableBody = updateGateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/admin/gates/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
