/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.shipeasy.admin.models.CreateConnectorResponse
import ai.shipeasy.admin.models.CreateTriggerConnectorRequest
import ai.shipeasy.admin.models.Error

import com.squareup.moshi.Json

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import ai.shipeasy.admin.infrastructure.ApiClient
import ai.shipeasy.admin.infrastructure.ApiResponse
import ai.shipeasy.admin.infrastructure.ClientException
import ai.shipeasy.admin.infrastructure.ClientError
import ai.shipeasy.admin.infrastructure.ServerException
import ai.shipeasy.admin.infrastructure.ServerError
import ai.shipeasy.admin.infrastructure.MultiValueMap
import ai.shipeasy.admin.infrastructure.PartConfig
import ai.shipeasy.admin.infrastructure.RequestConfig
import ai.shipeasy.admin.infrastructure.RequestMethod
import ai.shipeasy.admin.infrastructure.ResponseType
import ai.shipeasy.admin.infrastructure.Success
import ai.shipeasy.admin.infrastructure.toMultiValue

open class TriggerApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://shipeasy.ai")
        }
    }

    /**
     * POST /api/admin/connectors/trigger
     * Create a recurring coding-agent trigger
     * Creates (or idempotently updates) a coding-agent **trigger** connector — the recurring, unattended run that burns down the ops queue in &#x60;--pr&#x60; mode. Discriminated on &#x60;provider&#x60;; only the four Shipeasy-fireable providers are accepted (&#x60;claude_trigger&#x60;, &#x60;cursor_trigger&#x60;, &#x60;copilot_trigger&#x60;, &#x60;jules_trigger&#x60;). Config + credential(s) arrive together; creates are idempotent by the provider&#39;s natural key, so re-creating updates the existing row.  Platforms without a fire endpoint (Codex, Windsurf, Cline, OpenClaw, OpenCode, Continue) cannot be created here — they are scheduled on their own platform (typically a GitHub Actions &#x60;schedule:&#x60; cron running the platform&#39;s headless CLI with the trigger prompt).  **Use cases**  - **Register a Claude routine** — after &#x60;RemoteTrigger {action:\&quot;create\&quot;}&#x60; returns &#x60;trig_…&#x60;, &#x60;{ \&quot;provider\&quot;: \&quot;claude_trigger\&quot;, \&quot;config\&quot;: { \&quot;routineId\&quot;: \&quot;trig_…\&quot; } }&#x60; (tokenless is fine; add the fire token later). - **Cold Cursor/Jules run** — repo coordinates + both keys; Shipeasy launches the run and the PR opens via the provider&#39;s GitHub App. - **Copilot cloud agent** — repo + a Copilot-licensed user PAT with the \&quot;Agent tasks\&quot; permission.
     * @param createTriggerConnectorRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return CreateConnectorResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createTriggerConnector(createTriggerConnectorRequest: CreateTriggerConnectorRequest, xProjectId: kotlin.String? = null) : CreateConnectorResponse = withContext(Dispatchers.IO) {
        val localVarResponse = createTriggerConnectorWithHttpInfo(createTriggerConnectorRequest = createTriggerConnectorRequest, xProjectId = xProjectId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateConnectorResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/admin/connectors/trigger
     * Create a recurring coding-agent trigger
     * Creates (or idempotently updates) a coding-agent **trigger** connector — the recurring, unattended run that burns down the ops queue in &#x60;--pr&#x60; mode. Discriminated on &#x60;provider&#x60;; only the four Shipeasy-fireable providers are accepted (&#x60;claude_trigger&#x60;, &#x60;cursor_trigger&#x60;, &#x60;copilot_trigger&#x60;, &#x60;jules_trigger&#x60;). Config + credential(s) arrive together; creates are idempotent by the provider&#39;s natural key, so re-creating updates the existing row.  Platforms without a fire endpoint (Codex, Windsurf, Cline, OpenClaw, OpenCode, Continue) cannot be created here — they are scheduled on their own platform (typically a GitHub Actions &#x60;schedule:&#x60; cron running the platform&#39;s headless CLI with the trigger prompt).  **Use cases**  - **Register a Claude routine** — after &#x60;RemoteTrigger {action:\&quot;create\&quot;}&#x60; returns &#x60;trig_…&#x60;, &#x60;{ \&quot;provider\&quot;: \&quot;claude_trigger\&quot;, \&quot;config\&quot;: { \&quot;routineId\&quot;: \&quot;trig_…\&quot; } }&#x60; (tokenless is fine; add the fire token later). - **Cold Cursor/Jules run** — repo coordinates + both keys; Shipeasy launches the run and the PR opens via the provider&#39;s GitHub App. - **Copilot cloud agent** — repo + a Copilot-licensed user PAT with the \&quot;Agent tasks\&quot; permission.
     * @param createTriggerConnectorRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return ApiResponse<CreateConnectorResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createTriggerConnectorWithHttpInfo(createTriggerConnectorRequest: CreateTriggerConnectorRequest, xProjectId: kotlin.String?) : ApiResponse<CreateConnectorResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createTriggerConnectorRequestConfig(createTriggerConnectorRequest = createTriggerConnectorRequest, xProjectId = xProjectId)

        return@withContext request<CreateTriggerConnectorRequest, CreateConnectorResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createTriggerConnector
     *
     * @param createTriggerConnectorRequest 
     * @param xProjectId Project the request operates on. Optional — defaults to the project the SDK key belongs to; pass it only to scope a multi-project key (the generated client sets it once from its configuration, so per-call callers never thread it). (optional)
     * @return RequestConfig
     */
    fun createTriggerConnectorRequestConfig(createTriggerConnectorRequest: CreateTriggerConnectorRequest, xProjectId: kotlin.String?) : RequestConfig<CreateTriggerConnectorRequest> {
        val localVariableBody = createTriggerConnectorRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProjectId?.apply { localVariableHeaders["X-Project-Id"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/admin/connectors/trigger",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
