/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ConnectorEvent
import ai.shipeasy.admin.models.CopilotTriggerConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Create a GitHub Copilot coding-agent trigger. Idempotent by `config.owner/config.repo`.
 *
 * @param provider Discriminator. GitHub Copilot coding-agent trigger.
 * @param config 
 * @param token Copilot-licensed user PAT (secret). The ops key lives in the repo's GitHub \"Agents\" secret store and is never sent through Shipeasy. Encrypted; never returned.
 * @param name Human-readable connector label.
 * @param events Events that auto-fire a Copilot agent task. Defaults to empty.
 * @param enabled Whether the trigger is active on create.
 */


data class CreateCopilotTriggerRequest (

    /* Discriminator. GitHub Copilot coding-agent trigger. */
    @Json(name = "provider")
    val provider: CreateCopilotTriggerRequest.Provider,

    @Json(name = "config")
    val config: CopilotTriggerConfig,

    /* Copilot-licensed user PAT (secret). The ops key lives in the repo's GitHub \"Agents\" secret store and is never sent through Shipeasy. Encrypted; never returned. */
    @Json(name = "token")
    val token: kotlin.String,

    /* Human-readable connector label. */
    @Json(name = "name")
    val name: kotlin.String? = "Copilot trigger",

    /* Events that auto-fire a Copilot agent task. Defaults to empty. */
    @Json(name = "events")
    val events: kotlin.collections.List<ConnectorEvent>? = null,

    /* Whether the trigger is active on create. */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = true

) {

    /**
     * Discriminator. GitHub Copilot coding-agent trigger.
     *
     * Values: copilot_trigger
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "copilot_trigger") copilot_trigger("copilot_trigger");
    }

}

