/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ConnectorEvent
import ai.shipeasy.admin.models.JulesTriggerConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Create a Google Jules trigger. Both keys are required up front. Idempotent by `config.source`.
 *
 * @param provider Discriminator. Google Jules trigger.
 * @param config 
 * @param apiKey Jules API key that launches the session (secret). Encrypted into the credentials cipher; never returned.
 * @param opsKey Restricted Shipeasy ops key, embedded in the prompt (Jules exposes no env channel) (secret). Encrypted; never returned.
 * @param name Human-readable connector label.
 * @param events Events that auto-fire a Jules session. Defaults to empty.
 * @param enabled Whether the trigger is active on create.
 */


data class CreateJulesTriggerRequest (

    /* Discriminator. Google Jules trigger. */
    @Json(name = "provider")
    val provider: CreateJulesTriggerRequest.Provider,

    @Json(name = "config")
    val config: JulesTriggerConfig,

    /* Jules API key that launches the session (secret). Encrypted into the credentials cipher; never returned. */
    @Json(name = "apiKey")
    val apiKey: kotlin.String,

    /* Restricted Shipeasy ops key, embedded in the prompt (Jules exposes no env channel) (secret). Encrypted; never returned. */
    @Json(name = "opsKey")
    val opsKey: kotlin.String,

    /* Human-readable connector label. */
    @Json(name = "name")
    val name: kotlin.String? = "Jules trigger",

    /* Events that auto-fire a Jules session. Defaults to empty. */
    @Json(name = "events")
    val events: kotlin.collections.List<ConnectorEvent>? = null,

    /* Whether the trigger is active on create. */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = true

) {

    /**
     * Discriminator. Google Jules trigger.
     *
     * Values: jules_trigger
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "jules_trigger") jules_trigger("jules_trigger");
    }

}

