/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.NotificationTarget
import ai.shipeasy.admin.models.OpsItemPriority

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Feature-request-kind fields for `POST /api/admin/ops` (sent with `type: feature_request`).
 *
 * @param type Discriminator — files a feature request.
 * @param title One-line feature-request title (no leading/trailing whitespace).
 * @param description What the feature is.
 * @param useCase Why it's needed / the use case.
 * @param priority Initial triage priority, or `null`.
 * @param reporterEmail Email of the reporter, or `null`.
 * @param pageUrl URL of the page the request relates to, or `null`.
 * @param userAgent Reporter's user-agent string, or `null`.
 * @param context Arbitrary capture context, or `null`.
 * @param notify Where this request's completion notification lands.
 */


data class CreateFeatureRequestRequest (

    /* Discriminator — files a feature request. */
    @Json(name = "type")
    val type: CreateFeatureRequestRequest.Type,

    /* One-line feature-request title (no leading/trailing whitespace). */
    @Json(name = "title")
    val title: kotlin.String,

    /* What the feature is. */
    @Json(name = "description")
    val description: kotlin.String? = "",

    /* Why it's needed / the use case. */
    @Json(name = "useCase")
    val useCase: kotlin.String? = "",

    /* Initial triage priority, or `null`. */
    @Json(name = "priority")
    val priority: OpsItemPriority? = null,

    /* Email of the reporter, or `null`. */
    @Json(name = "reporterEmail")
    val reporterEmail: kotlin.String? = null,

    /* URL of the page the request relates to, or `null`. */
    @Json(name = "pageUrl")
    val pageUrl: java.net.URI? = null,

    /* Reporter's user-agent string, or `null`. */
    @Json(name = "userAgent")
    val userAgent: kotlin.String? = null,

    /* Arbitrary capture context, or `null`. */
    @Json(name = "context")
    val context: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Where this request's completion notification lands. */
    @Json(name = "notify")
    val notify: NotificationTarget? = null

) {

    /**
     * Discriminator — files a feature request.
     *
     * Values: feature_request
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "feature_request") feature_request("feature_request");
    }

}

