/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ConnectorEvent
import ai.shipeasy.admin.models.CursorTriggerConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Create a Cursor cloud-agent trigger. Both keys are required up front (never tokenless). Idempotent by `config.repoUrl`.
 *
 * @param provider Discriminator. Cursor cloud-agent trigger.
 * @param config 
 * @param apiKey Cursor API key that launches the run (secret). Encrypted into the credentials cipher; never returned.
 * @param opsKey Restricted Shipeasy ops key, injected into the run as `SHIPEASY_CLI_TOKEN` via the launch envVars (secret). Encrypted; never returned.
 * @param name Human-readable connector label.
 * @param events Events that auto-fire a cold cloud-agent run. Defaults to empty.
 * @param enabled Whether the trigger is active on create.
 */


data class CreateCursorTriggerRequest (

    /* Discriminator. Cursor cloud-agent trigger. */
    @Json(name = "provider")
    val provider: CreateCursorTriggerRequest.Provider,

    @Json(name = "config")
    val config: CursorTriggerConfig,

    /* Cursor API key that launches the run (secret). Encrypted into the credentials cipher; never returned. */
    @Json(name = "apiKey")
    val apiKey: kotlin.String,

    /* Restricted Shipeasy ops key, injected into the run as `SHIPEASY_CLI_TOKEN` via the launch envVars (secret). Encrypted; never returned. */
    @Json(name = "opsKey")
    val opsKey: kotlin.String,

    /* Human-readable connector label. */
    @Json(name = "name")
    val name: kotlin.String? = "Cursor trigger",

    /* Events that auto-fire a cold cloud-agent run. Defaults to empty. */
    @Json(name = "events")
    val events: kotlin.collections.List<ConnectorEvent>? = null,

    /* Whether the trigger is active on create. */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = true

) {

    /**
     * Discriminator. Cursor cloud-agent trigger.
     *
     * Values: cursor_trigger
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "cursor_trigger") cursor_trigger("cursor_trigger");
    }

}

