/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListEventsResponseInnerPropertiesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/events`. Only `name` is required.
 *
 * @param name Event name. Starts with a letter, digit, or `_`; letters, digits, `_`, `-`, `.`; max 128 chars. Immutable after create — this is the handle metric queries reference.
 * @param folder Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
 * @param description Optional human-readable description of the event.
 * @param properties Typed properties declared on the event. Defaults to an empty list.
 */


data class CreateEventRequest (

    /* Event name. Starts with a letter, digit, or `_`; letters, digits, `_`, `-`, `.`; max 128 chars. Immutable after create — this is the handle metric queries reference. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    @Json(name = "folder")
    val folder: kotlin.String? = null,

    /* Optional human-readable description of the event. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Typed properties declared on the event. Defaults to an empty list. */
    @Json(name = "properties")
    val properties: kotlin.collections.List<ListEventsResponseInnerPropertiesInner>? = null

) {


}

