/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListGatesResponseDataInnerRulesInner
import ai.shipeasy.admin.models.ListGatesResponseDataInnerStackInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/gates`. At minimum supply `name`; everything else has sensible defaults.
 *
 * @param name Stable gate key used by SDKs (`Shipeasy.checkGate(user, '<name>')`). Single segment or `folder.name`. Lowercase letters, digits, `_` or `-`; max 128 chars. Immutable after create — rename = delete + recreate.
 * @param enabled Master switch. Defaults to `true`. Set `false` to create the gate disabled (evaluates to `false` regardless of rules/rollout); flip on via `POST /{id}/enable` or PATCH.
 * @param rolloutPct Initial rollout in **basis points** (0–10000 = 0%–100%) — `100` here means **1%**, not 100%. Use `rollout_percent` (0–100) below if you'd rather think in percent. Use `0` to create the gate dark and ramp via PATCH after deploy validation.
 * @param rolloutPercent Initial rollout as a **percentage** (0–100, fractional ok). Friendlier alias for `rollout_pct`; converted internally to basis points (e.g. `100` here = 10000 bp = 100%). If both `rollout_pct` and `rollout_percent` are set, `rollout_percent` wins.
 * @param rules Targeting predicates. AND-combined. If non-empty, the gate returns `true` only for callers that satisfy every rule **and** fall under `rollout_pct`.
 * @param salt Hash salt for percentage bucketing. Auto-generated if omitted. Provide explicitly to keep a gate's buckets stable across delete/recreate. **Immutable after create** — there is no PATCH for `salt` because changing it would re-bucket every caller.
 * @param stack Optional gatekeeper stack. When provided, takes precedence over `rules` + `rollout_pct` at evaluation time. Omit (or pass `null`) for a flat gate.
 * @param title Human-readable title shown in the dashboard. Free-form, no key format constraint.
 * @param description Long-form description / runbook. Markdown is rendered in the dashboard.
 * @param folder Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
 * @param group Group label for dashboard organisation (e.g. team or product area).
 * @param ownerEmail Owner contact. Displayed verbatim; not used for auth.
 */


data class CreateGateRequest (

    /* Stable gate key used by SDKs (`Shipeasy.checkGate(user, '<name>')`). Single segment or `folder.name`. Lowercase letters, digits, `_` or `-`; max 128 chars. Immutable after create — rename = delete + recreate. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Master switch. Defaults to `true`. Set `false` to create the gate disabled (evaluates to `false` regardless of rules/rollout); flip on via `POST /{id}/enable` or PATCH. */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = true,

    /* Initial rollout in **basis points** (0–10000 = 0%–100%) — `100` here means **1%**, not 100%. Use `rollout_percent` (0–100) below if you'd rather think in percent. Use `0` to create the gate dark and ramp via PATCH after deploy validation. */
    @Json(name = "rollout_pct")
    val rolloutPct: kotlin.Int? = 0,

    /* Initial rollout as a **percentage** (0–100, fractional ok). Friendlier alias for `rollout_pct`; converted internally to basis points (e.g. `100` here = 10000 bp = 100%). If both `rollout_pct` and `rollout_percent` are set, `rollout_percent` wins. */
    @Json(name = "rollout_percent")
    val rolloutPercent: java.math.BigDecimal? = null,

    /* Targeting predicates. AND-combined. If non-empty, the gate returns `true` only for callers that satisfy every rule **and** fall under `rollout_pct`. */
    @Json(name = "rules")
    val rules: kotlin.collections.List<ListGatesResponseDataInnerRulesInner>? = null,

    /* Hash salt for percentage bucketing. Auto-generated if omitted. Provide explicitly to keep a gate's buckets stable across delete/recreate. **Immutable after create** — there is no PATCH for `salt` because changing it would re-bucket every caller. */
    @Json(name = "salt")
    val salt: kotlin.String? = null,

    /* Optional gatekeeper stack. When provided, takes precedence over `rules` + `rollout_pct` at evaluation time. Omit (or pass `null`) for a flat gate. */
    @Json(name = "stack")
    val stack: kotlin.collections.List<ListGatesResponseDataInnerStackInner>? = null,

    /* Human-readable title shown in the dashboard. Free-form, no key format constraint. */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Long-form description / runbook. Markdown is rendered in the dashboard. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    @Json(name = "folder")
    val folder: kotlin.String? = null,

    /* Group label for dashboard organisation (e.g. team or product area). */
    @Json(name = "group")
    val group: kotlin.String? = null,

    /* Owner contact. Displayed verbatim; not used for auth. */
    @Json(name = "owner_email")
    val ownerEmail: kotlin.String? = null

) {


}

