/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.GateTemplateRuleResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A reusable targeting-rule template. Built-ins are read-only (`builtin: true`, stable slug `id`); per-project customer templates are `builtin: false` with a `gtpl_…` id.
 *
 * @param id Stable slug for built-ins (`country`), `gtpl_…` for customer templates.
 * @param name Human label shown in pickers (`Country is`).
 * @param description One-liner — feeds the list `query` filter.
 * @param category `condition` = rule-based predicate, `rollout` = percentage bucket.
 * @param auto True when the attribute is request-derived (country/browser/…) and resolved at the SDK edge, so the caller need not pass it.
 * @param builtin Read-only built-in (`true`) vs editable customer template (`false`).
 * @param rules The rule definition — copy, substitute the value(s), pass as `rules`.
 * @param iconKey Display-only icon hint.
 * @param createdAt ISO-8601 creation timestamp; `null` for built-ins.
 * @param updatedAt ISO-8601 last-mutation timestamp; `null` for built-ins.
 */


data class GateTemplate (

    /* Stable slug for built-ins (`country`), `gtpl_…` for customer templates. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Human label shown in pickers (`Country is`). */
    @Json(name = "name")
    val name: kotlin.String,

    /* One-liner — feeds the list `query` filter. */
    @Json(name = "description")
    val description: kotlin.String,

    /* `condition` = rule-based predicate, `rollout` = percentage bucket. */
    @Json(name = "category")
    val category: GateTemplate.Category,

    /* True when the attribute is request-derived (country/browser/…) and resolved at the SDK edge, so the caller need not pass it. */
    @Json(name = "auto")
    val auto: kotlin.Boolean,

    /* Read-only built-in (`true`) vs editable customer template (`false`). */
    @Json(name = "builtin")
    val builtin: kotlin.Boolean,

    /* The rule definition — copy, substitute the value(s), pass as `rules`. */
    @Json(name = "rules")
    val rules: kotlin.collections.List<GateTemplateRuleResponse>,

    /* Display-only icon hint. */
    @Json(name = "iconKey")
    val iconKey: kotlin.String? = null,

    /* ISO-8601 creation timestamp; `null` for built-ins. */
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,

    /* ISO-8601 last-mutation timestamp; `null` for built-ins. */
    @Json(name = "updatedAt")
    val updatedAt: kotlin.String? = null

) {

    /**
     * `condition` = rule-based predicate, `rollout` = percentage bucket.
     *
     * Values: condition,rollout
     */
    @JsonClass(generateAdapter = false)
    enum class Category(val value: kotlin.String) {
        @Json(name = "condition") condition("condition"),
        @Json(name = "rollout") rollout("rollout");
    }

}

