/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param metric 
 * @param groupName 
 * @param ds Date slice (`YYYY-MM-DD`).
 * @param n 
 * @param mean 
 * @param deltaPct 
 * @param pValue 
 * @param srmDetected `1` if sample-ratio mismatch detected, else `0`.
 */


data class GetExperimentTimeseriesResponseSeriesInner (

    @Json(name = "metric")
    val metric: kotlin.String,

    @Json(name = "group_name")
    val groupName: kotlin.String,

    /* Date slice (`YYYY-MM-DD`). */
    @Json(name = "ds")
    val ds: kotlin.String,

    @Json(name = "n")
    val n: java.math.BigDecimal?,

    @Json(name = "mean")
    val mean: java.math.BigDecimal?,

    @Json(name = "delta_pct")
    val deltaPct: java.math.BigDecimal?,

    @Json(name = "p_value")
    val pValue: java.math.BigDecimal?,

    /* `1` if sample-ratio mismatch detected, else `0`. */
    @Json(name = "srm_detected")
    val srmDetected: java.math.BigDecimal?

) {


}

