/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.GetExperimentResultsResponseExperiment
import ai.shipeasy.admin.models.GetExperimentTimeseriesResponseSeriesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param experiment 
 * @param series 
 */


data class GetExperimentTimeseriesResponse (

    @Json(name = "experiment")
    val experiment: GetExperimentResultsResponseExperiment,

    @Json(name = "series")
    val series: kotlin.collections.List<GetExperimentTimeseriesResponseSeriesInner>

) {


}

