/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListEventsResponseInnerPropertiesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A catalogued event.
 *
 * @param id Stable opaque event id.
 * @param name Event name — the handle metric queries reference.
 * @param description Human-readable description, or `null` if none set.
 * @param properties Typed properties declared on the event.
 * @param pending `1` if this is an auto-discovered name awaiting approval (metrics on it fail until approved), `0` if approved/usable.
 * @param createdAt ISO-8601 timestamp of creation.
 * @param folder Optional folder name used to group items in the dashboard. Part of the SDK lookup key: an item in folder `checkout` named `new-cart` is referenced as `checkout/new-cart` from the SDK.
 */


data class GetEventResponse (

    /* Stable opaque event id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Event name — the handle metric queries reference. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Human-readable description, or `null` if none set. */
    @Json(name = "description")
    val description: kotlin.String?,

    /* Typed properties declared on the event. */
    @Json(name = "properties")
    val properties: kotlin.collections.List<ListEventsResponseInnerPropertiesInner>,

    /* `1` if this is an auto-discovered name awaiting approval (metrics on it fail until approved), `0` if approved/usable. */
    @Json(name = "pending")
    val pending: kotlin.Int,

    /* ISO-8601 timestamp of creation. */
    @Json(name = "createdAt")
    val createdAt: kotlin.String,

    /* Optional folder name used to group items in the dashboard. Part of the SDK lookup key: an item in folder `checkout` named `new-cart` is referenced as `checkout/new-cart` from the SDK. */
    @Json(name = "folder")
    val folder: kotlin.String? = null

) {


}

