/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Non-secret config for a Jules trigger.
 *
 * @param source Jules source for the connected repo, e.g. `sources/github/owner/repo`. Idempotency key for the connector.
 * @param projectId Shipeasy project id the run targets.
 * @param startingBranch Optional branch the session starts from.
 */


data class JulesTriggerConfig (

    /* Jules source for the connected repo, e.g. `sources/github/owner/repo`. Idempotency key for the connector. */
    @Json(name = "source")
    val source: kotlin.String,

    /* Shipeasy project id the run targets. */
    @Json(name = "projectId")
    val projectId: kotlin.String,

    /* Optional branch the session starts from. */
    @Json(name = "startingBranch")
    val startingBranch: kotlin.String? = null

) {


}

