/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListKillswitchesResponseDataInnerEnvsValue

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Stable opaque killswitch id.
 * @param name Stable config key in `folder.name` form (two lowercase segments separated by a dot, e.g. `pricing.tiers`). Used by SDKs as `Shipeasy.getConfig('<name>')`. Immutable after create.
 * @param description Free-form description or `null`.
 * @param updatedAt ISO-8601 timestamp of last mutation.
 * @param envs Per-env latest value, switches, version, and publish timestamp.
 */


data class ListKillswitchesResponseDataInner (

    /* Stable opaque killswitch id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Stable config key in `folder.name` form (two lowercase segments separated by a dot, e.g. `pricing.tiers`). Used by SDKs as `Shipeasy.getConfig('<name>')`. Immutable after create. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Free-form description or `null`. */
    @Json(name = "description")
    val description: kotlin.String?,

    /* ISO-8601 timestamp of last mutation. */
    @Json(name = "updatedAt")
    val updatedAt: kotlin.String,

    /* Per-env latest value, switches, version, and publish timestamp. */
    @Json(name = "envs")
    val envs: kotlin.collections.Map<kotlin.String, ListKillswitchesResponseDataInnerEnvsValue>

) {


}

