/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListGatesResponseDataInnerStackInnerOneOfRamp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Percentage-rollout sub-gate. Hashes `bucketBy` (default `userID`) with `salt` and returns `true` for `rolloutPct/10000` fraction of callers (or the ramp's effective % when `ramp` is set).
 *
 * @param id Client-supplied stable id for the stack entry.
 * @param type Discriminator. `rollout` = percentage-bucket sub-gate.
 * @param rolloutPct Bucket size in basis points (0–10000 = 0%–100%). `5000` = 50%, `100` = 1%, allows sub-1% precision.
 * @param name Human label shown in the dashboard.
 * @param fromTemplate Source template id, or `null`.
 * @param bucketBy Attribute used to hash the caller into a bucket. Defaults to `user.userID`. Use e.g. `accountID` to bucket whole accounts together.
 * @param salt Per-entry hash salt. Defaults to the gate's salt. Set explicitly to keep two rollouts independent or correlated across gates.
 * @param ramp 
 * @param locked If `true`, dashboard hides edit controls.
 */


data class ListGatesResponseDataInnerStackInnerOneOf1 (

    /* Client-supplied stable id for the stack entry. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Discriminator. `rollout` = percentage-bucket sub-gate. */
    @Json(name = "type")
    val type: ListGatesResponseDataInnerStackInnerOneOf1.Type,

    /* Bucket size in basis points (0–10000 = 0%–100%). `5000` = 50%, `100` = 1%, allows sub-1% precision. */
    @Json(name = "rolloutPct")
    val rolloutPct: kotlin.Int,

    /* Human label shown in the dashboard. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Source template id, or `null`. */
    @Json(name = "fromTemplate")
    val fromTemplate: kotlin.String? = null,

    /* Attribute used to hash the caller into a bucket. Defaults to `user.userID`. Use e.g. `accountID` to bucket whole accounts together. */
    @Json(name = "bucketBy")
    val bucketBy: kotlin.String? = null,

    /* Per-entry hash salt. Defaults to the gate's salt. Set explicitly to keep two rollouts independent or correlated across gates. */
    @Json(name = "salt")
    val salt: kotlin.String? = null,

    @Json(name = "ramp")
    val ramp: ListGatesResponseDataInnerStackInnerOneOfRamp? = null,

    /* If `true`, dashboard hides edit controls. */
    @Json(name = "locked")
    val locked: kotlin.Boolean? = null

) {

    /**
     * Discriminator. `rollout` = percentage-bucket sub-gate.
     *
     * Values: rollout
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "rollout") rollout("rollout");
    }

}

