/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param updatedAt ISO-8601 last-edit timestamp on the draft.
 * @param authorEmail Email/id of the actor who last edited the draft.
 * @param baseVersion Published version the draft was forked from.
 */


data class ListConfigsResponseDataInnerDraftsValue (

    /* ISO-8601 last-edit timestamp on the draft. */
    @Json(name = "updatedAt")
    val updatedAt: kotlin.String,

    /* Email/id of the actor who last edited the draft. */
    @Json(name = "authorEmail")
    val authorEmail: kotlin.String,

    /* Published version the draft was forked from. */
    @Json(name = "baseVersion")
    val baseVersion: kotlin.Int

) {


}

