/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param version Monotonically increasing version per env.
 * @param publishedAt ISO-8601 publish timestamp.
 * @param publishedBy Email/id of the actor who published this version.
 */


data class ListConfigsResponseDataInnerEnvsValue (

    /* Monotonically increasing version per env. */
    @Json(name = "version")
    val version: kotlin.Int,

    /* ISO-8601 publish timestamp. */
    @Json(name = "publishedAt")
    val publishedAt: kotlin.String,

    /* Email/id of the actor who published this version. */
    @Json(name = "publishedBy")
    val publishedBy: kotlin.String

) {


}

