/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A resource referenced by a measurement plan.
 *
 * @param kind Resource kind.
 * @param name Resource name.
 * @param id Resource id when it was created; absent/`null` for resources still to be made.
 */


data class MeasurePlanResource (

    /* Resource kind. */
    @Json(name = "kind")
    val kind: MeasurePlanResource.Kind,

    /* Resource name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Resource id when it was created; absent/`null` for resources still to be made. */
    @Json(name = "id")
    val id: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {

    /**
     * Resource kind.
     *
     * Values: metric,experiment,alert_rule,event
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "metric") metric("metric"),
        @Json(name = "experiment") experiment("experiment"),
        @Json(name = "alert_rule") alert_rule("alert_rule"),
        @Json(name = "event") event("event");
    }

}

