/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The metric an alert watches, with its backing events.
 *
 * @param id Metric id (fetch full detail via `related.metric`).
 * @param name Metric name.
 * @param events The event name(s) the metric aggregates over — one for count metrics, numerator + denominator for ratio metrics. Grep the codebase for `track('<event>')` on each to find the instrumentation feeding the metric.
 */


data class OpsAlertMetricSummary (

    /* Metric id (fetch full detail via `related.metric`). */
    @Json(name = "id")
    val id: kotlin.String,

    /* Metric name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The event name(s) the metric aggregates over — one for count metrics, numerator + denominator for ratio metrics. Grep the codebase for `track('<event>')` on each to find the instrumentation feeding the metric. */
    @Json(name = "events")
    val events: kotlin.collections.List<kotlin.String>

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

