/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Auto-collected browser environment for a `bug`/`feature_request`, captured at file time.
 *
 * @param pageUrl URL of the page the report was filed from, or `null`.
 * @param userAgent Reporter's user-agent string, or `null`.
 * @param viewport Reporter's viewport (e.g. `1280x720`), or `null`.
 */


data class OpsBrowserContext (

    /* URL of the page the report was filed from, or `null`. */
    @Json(name = "pageUrl")
    val pageUrl: kotlin.String? = null,

    /* Reporter's user-agent string, or `null`. */
    @Json(name = "userAgent")
    val userAgent: kotlin.String? = null,

    /* Reporter's viewport (e.g. `1280x720`), or `null`. */
    @Json(name = "viewport")
    val viewport: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

