/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Hydrated detail for an auto-filed `error` ticket, read from the tracked `errors` row at request time (so `count`/`lastSeenAt` reflect the latest state).
 *
 * @param id The tracked `errors` row id (fetch full detail via `related.error`).
 * @param fingerprint Stable dedupe key of the tracked error.
 * @param message The error message.
 * @param count Folded occurrence count for this fingerprint.
 * @param firstSeenAt ISO-8601 timestamp of the first occurrence.
 * @param lastSeenAt ISO-8601 timestamp of the most recent occurrence.
 * @param seenUrls Distinct, id-normalized routes this error has surfaced on (UUIDs/ids collapsed to `#`).
 * @param causedByFingerprint Fingerprint of the upstream issue this error descends from (set when the same error was reported at an inner boundary first), or `null` for a root issue.
 * @param errorType Error class/name, e.g. `TypeError`, or `null` when the source didn't supply one.
 * @param subject The `see()` consequence subject — the `causes_the(<subject>)` value. Grep the codebase for this to find the throw site. `null` if the error was never instrumented.
 * @param outcome The `see()` consequence outcome — the `.to(<outcome>)` value. `null` if uninstrumented.
 * @param kind `see()` error kind: `caught` | `uncaught` | `unhandled_rejection` | `network` | `violation`.
 * @param side Which SDK side reported it: `client` | `server`.
 * @param env Published env the reporting SDK ran against (dev/staging/prod).
 * @param stackTail The last 3 non-empty lines of the latest occurrence's stack — the innermost frames closest to where the throw bubbled out, baked in as an at-a-glance locator. `null` when the source supplied no stack. Fetch the full stack via `related.error`.
 * @param sdkVersion @shipeasy/sdk version of the latest occurrence, or `null`.
 */


data class OpsErrorContext (

    /* The tracked `errors` row id (fetch full detail via `related.error`). */
    @Json(name = "id")
    val id: kotlin.String,

    /* Stable dedupe key of the tracked error. */
    @Json(name = "fingerprint")
    val fingerprint: kotlin.String,

    /* The error message. */
    @Json(name = "message")
    val message: kotlin.String,

    /* Folded occurrence count for this fingerprint. */
    @Json(name = "count")
    val count: java.math.BigDecimal,

    /* ISO-8601 timestamp of the first occurrence. */
    @Json(name = "firstSeenAt")
    val firstSeenAt: kotlin.String,

    /* ISO-8601 timestamp of the most recent occurrence. */
    @Json(name = "lastSeenAt")
    val lastSeenAt: kotlin.String,

    /* Distinct, id-normalized routes this error has surfaced on (UUIDs/ids collapsed to `#`). */
    @Json(name = "seenUrls")
    val seenUrls: kotlin.collections.List<kotlin.String>,

    /* Fingerprint of the upstream issue this error descends from (set when the same error was reported at an inner boundary first), or `null` for a root issue. */
    @Json(name = "causedByFingerprint")
    val causedByFingerprint: kotlin.String? = null,

    /* Error class/name, e.g. `TypeError`, or `null` when the source didn't supply one. */
    @Json(name = "errorType")
    val errorType: kotlin.String? = null,

    /* The `see()` consequence subject — the `causes_the(<subject>)` value. Grep the codebase for this to find the throw site. `null` if the error was never instrumented. */
    @Json(name = "subject")
    val subject: kotlin.String? = null,

    /* The `see()` consequence outcome — the `.to(<outcome>)` value. `null` if uninstrumented. */
    @Json(name = "outcome")
    val outcome: kotlin.String? = null,

    /* `see()` error kind: `caught` | `uncaught` | `unhandled_rejection` | `network` | `violation`. */
    @Json(name = "kind")
    val kind: kotlin.String? = null,

    /* Which SDK side reported it: `client` | `server`. */
    @Json(name = "side")
    val side: kotlin.String? = null,

    /* Published env the reporting SDK ran against (dev/staging/prod). */
    @Json(name = "env")
    val env: kotlin.String? = null,

    /* The last 3 non-empty lines of the latest occurrence's stack — the innermost frames closest to where the throw bubbled out, baked in as an at-a-glance locator. `null` when the source supplied no stack. Fetch the full stack via `related.error`. */
    @Json(name = "stackTail")
    val stackTail: kotlin.String? = null,

    /* @shipeasy/sdk version of the latest occurrence, or `null`. */
    @Json(name = "sdkVersion")
    val sdkVersion: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

