/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.OpsAlertContext
import ai.shipeasy.admin.models.OpsBrowserContext
import ai.shipeasy.admin.models.OpsErrorContext
import ai.shipeasy.admin.models.OpsMeasurePlanContext

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Per-type capture context on a queue item. Exactly one of `browser` (bug/feature), `error`, `alert`, or `measurePlan` is populated depending on `type`; other keys (e.g. the AI dedupe block on bugs) may also be present.
 *
 * @param browser 
 * @param error 
 * @param alert 
 * @param measurePlan 
 */


data class OpsItemContext (

    @Json(name = "browser")
    val browser: OpsBrowserContext? = null,

    @Json(name = "error")
    val error: OpsErrorContext? = null,

    @Json(name = "alert")
    val alert: OpsAlertContext? = null,

    @Json(name = "measurePlan")
    val measurePlan: OpsMeasurePlanContext? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

