/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param key Dotted key path, e.g. `home.cta`.
 * @param `value` Translated value for the key.
 * @param description Optional human note stored with the key.
 * @param variables Optional explicit list of `{{var}}` placeholder names in the value. Auto-derived from the value when omitted.
 */


data class PushI18nKeysRequestKeysInner (

    /* Dotted key path, e.g. `home.cta`. */
    @Json(name = "key")
    val key: kotlin.String,

    /* Translated value for the key. */
    @Json(name = "value")
    val `value`: kotlin.String,

    /* Optional human note stored with the key. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Optional explicit list of `{{var}}` placeholder names in the value. Auto-derived from the value when omitted. */
    @Json(name = "variables")
    val variables: kotlin.collections.List<kotlin.String>? = null

) {


}

