/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.QueryIrAggOneOf9Numerator

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param numerator 
 * @param denominator 
 */


data class QueryIrAggOneOf9 (

    @Json(name = "kind")
    val kind: QueryIrAggOneOf9.Kind,

    @Json(name = "numerator")
    val numerator: QueryIrAggOneOf9Numerator,

    @Json(name = "denominator")
    val denominator: QueryIrAggOneOf9Numerator

) {

    /**
     * 
     *
     * Values: ratio
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "ratio") ratio("ratio");
    }

}

