/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param p Quantile fraction (0.5 = p50 … 0.999 = p999).
 */


data class QueryIrAggOneOf7 (

    @Json(name = "kind")
    val kind: QueryIrAggOneOf7.Kind,

    /* Quantile fraction (0.5 = p50 … 0.999 = p999). */
    @Json(name = "p")
    val p: QueryIrAggOneOf7.P

) {

    /**
     * 
     *
     * Values: quantile
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "quantile") quantile("quantile");
    }
    /**
     * Quantile fraction (0.5 = p50 … 0.999 = p999).
     *
     * Values: _0Period5,_0Period75,_0Period9,_0Period95,_0Period99,_0Period999
     */
    @JsonClass(generateAdapter = false)
    enum class P(val value: java.math.BigDecimal) {
        @Json(name = "0.5") _0Period5(java.math.BigDecimal("0.5")),
        @Json(name = "0.75") _0Period75(java.math.BigDecimal("0.75")),
        @Json(name = "0.9") _0Period9(java.math.BigDecimal("0.9")),
        @Json(name = "0.95") _0Period95(java.math.BigDecimal("0.95")),
        @Json(name = "0.99") _0Period99(java.math.BigDecimal("0.99")),
        @Json(name = "0.999") _0Period999(java.math.BigDecimal("0.999"));
    }

}

