/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One label filter on the source event.
 *
 * @param label Event property / label identifier.
 * @param op Match operator (`=~`/`!~` are regex).
 * @param `value` Quoted filter value (coerced for numeric labels).
 */


data class QueryIrAggOneOf9NumeratorFiltersInner (

    /* Event property / label identifier. */
    @Json(name = "label")
    val label: kotlin.String,

    /* Match operator (`=~`/`!~` are regex). */
    @Json(name = "op")
    val op: QueryIrAggOneOf9NumeratorFiltersInner.Op,

    /* Quoted filter value (coerced for numeric labels). */
    @Json(name = "value")
    val `value`: kotlin.String

) {

    /**
     * Match operator (`=~`/`!~` are regex).
     *
     * Values: Equal,ExclamationEqual,EqualTilde,ExclamationTilde
     */
    @JsonClass(generateAdapter = false)
    enum class Op(val value: kotlin.String) {
        @Json(name = "=") Equal("="),
        @Json(name = "!=") ExclamationEqual("!="),
        @Json(name = "=~") EqualTilde("=~"),
        @Json(name = "!~") ExclamationTilde("!~");
    }

}

