/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Confirms the key is revoked. Idempotent — revoking an already-revoked key returns the same shape.
 *
 * @param id Id of the key that was revoked.
 * @param revoked 
 */


data class RevokeKeyResponse (

    /* Id of the key that was revoked. */
    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "revoked")
    val revoked: kotlin.Boolean

) {


}

