/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.Env

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param env 
 * @param baseVersion Published version the draft is based on.
 * @param updatedAt 
 */


data class SaveConfigDraftResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "env")
    val env: Env,

    /* Published version the draft is based on. */
    @Json(name = "baseVersion")
    val baseVersion: kotlin.Int,

    @Json(name = "updatedAt")
    val updatedAt: kotlin.String

) {


}

