/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A single universal-search hit. Field names are camelCase; `title` is `null` when the resource has no human title/display name (members fall back to a role label).
 *
 * @param type Resource family — drives the result group + icon in the palette. (`member` hits are surfaced first.)
 * @param id Stable identifier used to deep-link into the row's detail pane. For `member` hits this is the teammate's email; for everything else it is the resource id.
 * @param name The matched handle — the resource's immutable `name`, or the member's display name (falling back to email).
 * @param title Human title/display name when present, else `null`. For `member` hits this carries the email (or the `Owner`/`Member` role when no profile name is set).
 * @param href Project-relative href that opens the row (e.g. `/gates?open=<id>`).
 */


data class SearchHit (

    /* Resource family — drives the result group + icon in the palette. (`member` hits are surfaced first.) */
    @Json(name = "type")
    val type: SearchHit.Type,

    /* Stable identifier used to deep-link into the row's detail pane. For `member` hits this is the teammate's email; for everything else it is the resource id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The matched handle — the resource's immutable `name`, or the member's display name (falling back to email). */
    @Json(name = "name")
    val name: kotlin.String,

    /* Human title/display name when present, else `null`. For `member` hits this carries the email (or the `Owner`/`Member` role when no profile name is set). */
    @Json(name = "title")
    val title: kotlin.String?,

    /* Project-relative href that opens the row (e.g. `/gates?open=<id>`). */
    @Json(name = "href")
    val href: kotlin.String

) {

    /**
     * Resource family — drives the result group + icon in the palette. (`member` hits are surfaced first.)
     *
     * Values: member,gate,experiment,config,killswitch,metric
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "member") member("member"),
        @Json(name = "gate") gate("gate"),
        @Json(name = "experiment") experiment("experiment"),
        @Json(name = "config") config("config"),
        @Json(name = "killswitch") killswitch("killswitch"),
        @Json(name = "metric") metric("metric");
    }

}

