/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.Env

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `DELETE /api/admin/killswitches/{id}/switch`. Removes one switch entry from one env.
 *
 * @param env 
 * @param switchKey Switch key to remove.
 */


data class UnsetKillswitchSwitchRequest (

    @Json(name = "env")
    val env: Env,

    /* Switch key to remove. */
    @Json(name = "switchKey")
    val switchKey: kotlin.String

) {


}

