/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListGatesResponseDataInnerRulesInner
import ai.shipeasy.admin.models.ListGatesResponseDataInnerStackInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `PATCH /api/admin/gates/{id}`. Partial — only supplied fields change. Array fields (`rules`, `stack`) replace, not merge.
 *
 * @param rolloutPct New rollout in **basis points** (0–10000 = 0%–100%) — `100` here means **1%**. Use `rollout_percent` (0–100) below for percent. Omit both to leave unchanged.
 * @param rolloutPercent New rollout as a **percentage** (0–100). Friendlier alias for `rollout_pct`; converted internally. Wins over `rollout_pct` if both are supplied. Omit both to leave unchanged.
 * @param rules Replaces the rule list wholesale. To add a value to an `in` rule, send the full new `rules` array with the augmented `value` (e.g. previous `['US','CA']` → `['US','CA','GB']`).
 * @param enabled Master switch. `false` makes the gate evaluate to `false` for every caller regardless of `rollout_pct`, `rules`, or `stack` — use as kill switch.
 * @param stack Replaces the gatekeeper stack wholesale. Send `null` to revert to flat `rules` + `rollout_pct` evaluation.
 * @param title Human-readable title shown in the dashboard. Free-form, no key format constraint.
 * @param description Long-form description / runbook. Markdown is rendered in the dashboard.
 * @param folder Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
 * @param group Group label for dashboard organisation (e.g. team or product area).
 * @param ownerEmail Owner contact. Displayed verbatim; not used for auth.
 */


data class UpdateGateRequest (

    /* New rollout in **basis points** (0–10000 = 0%–100%) — `100` here means **1%**. Use `rollout_percent` (0–100) below for percent. Omit both to leave unchanged. */
    @Json(name = "rollout_pct")
    val rolloutPct: kotlin.Int? = null,

    /* New rollout as a **percentage** (0–100). Friendlier alias for `rollout_pct`; converted internally. Wins over `rollout_pct` if both are supplied. Omit both to leave unchanged. */
    @Json(name = "rollout_percent")
    val rolloutPercent: java.math.BigDecimal? = null,

    /* Replaces the rule list wholesale. To add a value to an `in` rule, send the full new `rules` array with the augmented `value` (e.g. previous `['US','CA']` → `['US','CA','GB']`). */
    @Json(name = "rules")
    val rules: kotlin.collections.List<ListGatesResponseDataInnerRulesInner>? = null,

    /* Master switch. `false` makes the gate evaluate to `false` for every caller regardless of `rollout_pct`, `rules`, or `stack` — use as kill switch. */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    /* Replaces the gatekeeper stack wholesale. Send `null` to revert to flat `rules` + `rollout_pct` evaluation. */
    @Json(name = "stack")
    val stack: kotlin.collections.List<ListGatesResponseDataInnerStackInner>? = null,

    /* Human-readable title shown in the dashboard. Free-form, no key format constraint. */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Long-form description / runbook. Markdown is rendered in the dashboard. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    @Json(name = "folder")
    val folder: kotlin.String? = null,

    /* Group label for dashboard organisation (e.g. team or product area). */
    @Json(name = "group")
    val group: kotlin.String? = null,

    /* Owner contact. Displayed verbatim; not used for auth. */
    @Json(name = "owner_email")
    val ownerEmail: kotlin.String? = null

) {


}

