/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.OpsItemNotifyOrNull
import ai.shipeasy.admin.models.OpsItemPriorityOrNull
import ai.shipeasy.admin.models.OpsItemStatus
import ai.shipeasy.admin.models.UpdateBugRequest
import ai.shipeasy.admin.models.UpdateFeatureRequestRequest
import ai.shipeasy.admin.models.UpdateOpsItemStatusRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `PATCH /api/admin/ops/{handle}`. The body is type-less — the server validates it against the stored item's type: a `bug` accepts the bug content fields, a `feature_request` the feature fields, and `error`/`alert`/`measure_plan` only `status`/`priority`/`notify`. Pass at least one field.
 *
 * @param title New feature-request title (no leading/trailing whitespace).
 * @param stepsToReproduce Updated reproduction steps.
 * @param actualResult Updated actual result.
 * @param expectedResult Updated expected result.
 * @param status 
 * @param priority 
 * @param githubPrNumber Link (or, when `null`, unlink) a GitHub pull request to this request.
 * @param notify 
 * @param description Updated description.
 * @param useCase Updated use case.
 */


data class UpdateOpsItemRequest (

    /* New feature-request title (no leading/trailing whitespace). */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Updated reproduction steps. */
    @Json(name = "stepsToReproduce")
    val stepsToReproduce: kotlin.String? = null,

    /* Updated actual result. */
    @Json(name = "actualResult")
    val actualResult: kotlin.String? = null,

    /* Updated expected result. */
    @Json(name = "expectedResult")
    val expectedResult: kotlin.String? = null,

    @Json(name = "status")
    val status: OpsItemStatus? = null,

    @Json(name = "priority")
    val priority: OpsItemPriorityOrNull? = null,

    /* Link (or, when `null`, unlink) a GitHub pull request to this request. */
    @Json(name = "githubPrNumber")
    val githubPrNumber: kotlin.Int? = null,

    @Json(name = "notify")
    val notify: OpsItemNotifyOrNull? = null,

    /* Updated description. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Updated use case. */
    @Json(name = "useCase")
    val useCase: kotlin.String? = null

) {


}

