/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.OpsItemNotifyOrNull
import ai.shipeasy.admin.models.OpsItemPriorityOrNull
import ai.shipeasy.admin.models.OpsItemStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Triage-only update — the shape accepted for any item, and the ONLY shape for auto-filed `error`/`alert`/`measure_plan` tickets (their content is not user-editable).
 *
 * @param status 
 * @param priority 
 * @param notify 
 */


data class UpdateOpsItemStatusRequest (

    @Json(name = "status")
    val status: OpsItemStatus? = null,

    @Json(name = "priority")
    val priority: OpsItemPriorityOrNull? = null,

    @Json(name = "notify")
    val notify: OpsItemNotifyOrNull? = null

) {


}

