/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.MetricDirection

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Update-metric variant that replaces the query with a `query` DSL string.
 *
 * @param query Metric query DSL string, e.g. `sum(purchase, amount)`. The alternative to `query_ir`. Every label the query references — in filters, the value position, `by (…)`, or `without (…)` — must exist as a property on the tracked event's payload; a query over a label the event never carries validates fine but returns empty results.
 * @param folder Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
 * @param eventName Source event the query reads from.
 * @param winsorizePct Winsorise percentile (1–99) to clamp outliers. Defaults to 99.
 * @param defaultMinEffectOfInterest Default minimum effect of interest (relative, 0–1) — the smallest change in this metric worth acting on, used as the power-planning baseline. Intrinsic to the metric; an experiment overrides it per-attachment with `min_effect_of_interest` when a specific decision has a different cost/risk bar. `null` to omit.
 * @param direction 
 */


data class UpdateMetricWithQuery (

    /* Metric query DSL string, e.g. `sum(purchase, amount)`. The alternative to `query_ir`. Every label the query references — in filters, the value position, `by (…)`, or `without (…)` — must exist as a property on the tracked event's payload; a query over a label the event never carries validates fine but returns empty results. */
    @Json(name = "query")
    val query: kotlin.String,

    /* Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    @Json(name = "folder")
    val folder: kotlin.String? = null,

    /* Source event the query reads from. */
    @Json(name = "event_name")
    val eventName: kotlin.String? = null,

    /* Winsorise percentile (1–99) to clamp outliers. Defaults to 99. */
    @Json(name = "winsorize_pct")
    val winsorizePct: kotlin.Int? = 99,

    /* Default minimum effect of interest (relative, 0–1) — the smallest change in this metric worth acting on, used as the power-planning baseline. Intrinsic to the metric; an experiment overrides it per-attachment with `min_effect_of_interest` when a specific decision has a different cost/risk bar. `null` to omit. */
    @Json(name = "default_min_effect_of_interest")
    val defaultMinEffectOfInterest: java.math.BigDecimal? = null,

    @Json(name = "direction")
    val direction: MetricDirection? = MetricDirection.higher_better

) {


}

