/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ExperimentInlineMetric
import ai.shipeasy.admin.models.ListExperimentsResponseDataInnerGroupsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `PATCH /api/admin/experiments/{id}`. Partial — only supplied fields change. `allocation_pct`, `groups`, `salt`, `universe`, `params` are immutable while the experiment is running (stop first).
 *
 * @param name Stable experiment key. Single segment or `folder.name` (a-z, 0-9, `_`/`-`; max 128 chars). Used by SDKs as `Shipeasy.getExperiment(user, '<name>')`. Immutable after create.
 * @param description 
 * @param hypothesis 
 * @param tag 
 * @param ownerEmail 
 * @param audience 
 * @param bucketBy User-attribute name used as the bucketing key — e.g. `user_id` (default), `session_id`, `device_id`, or a custom attribute like `company_id` to keep a whole org on one variant. Defaults to `user_id` when omitted.
 * @param folder Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
 * @param targetingGate 
 * @param allocationPct Basis-points allocation (0–10000). Use `allocation_percent` (0–100) for percent. Immutable while the experiment is running.
 * @param allocationPercent Allocation as a **percentage** (0–100). Friendlier alias for `allocation_pct`; converted to basis points server-side. Wins over `allocation_pct` if both are supplied. Immutable while running.
 * @param salt Hash salt. Immutable while running.
 * @param universe New universe name. Immutable while running. Returns `422` if the universe doesn't exist.
 * @param params Map of param-name → scalar type. Defines the shape of `groups[].params`. Example: `{ headline: 'string', show_cta: 'bool' }`.
 * @param groups Replacement groups. Weights must sum to 10000. Immutable while running.
 * @param significanceThreshold 
 * @param minRuntimeDays 
 * @param minSampleSize 
 * @param sequentialTesting 
 * @param goalMetric Replaces the goal metric — DSL `query` or `event` (+`aggregation`/`value`) the server compiles (event auto-upserted).
 * @param guardrailMetrics Replaces the guardrail set wholesale (event auto-upserted per entry).
 */


data class UpdateExperimentRequest (

    /* Stable experiment key. Single segment or `folder.name` (a-z, 0-9, `_`/`-`; max 128 chars). Used by SDKs as `Shipeasy.getExperiment(user, '<name>')`. Immutable after create. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "hypothesis")
    val hypothesis: kotlin.String? = null,

    @Json(name = "tag")
    val tag: kotlin.String? = null,

    @Json(name = "owner_email")
    val ownerEmail: kotlin.String? = null,

    @Json(name = "audience")
    val audience: kotlin.String? = null,

    /* User-attribute name used as the bucketing key — e.g. `user_id` (default), `session_id`, `device_id`, or a custom attribute like `company_id` to keep a whole org on one variant. Defaults to `user_id` when omitted. */
    @Json(name = "bucket_by")
    val bucketBy: kotlin.String? = null,

    /* Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    @Json(name = "folder")
    val folder: kotlin.String? = null,

    @Json(name = "targeting_gate")
    val targetingGate: kotlin.String? = null,

    /* Basis-points allocation (0–10000). Use `allocation_percent` (0–100) for percent. Immutable while the experiment is running. */
    @Json(name = "allocation_pct")
    val allocationPct: kotlin.Int? = null,

    /* Allocation as a **percentage** (0–100). Friendlier alias for `allocation_pct`; converted to basis points server-side. Wins over `allocation_pct` if both are supplied. Immutable while running. */
    @Json(name = "allocation_percent")
    val allocationPercent: java.math.BigDecimal? = null,

    /* Hash salt. Immutable while running. */
    @Json(name = "salt")
    val salt: kotlin.String? = null,

    /* New universe name. Immutable while running. Returns `422` if the universe doesn't exist. */
    @Json(name = "universe")
    val universe: kotlin.String? = null,

    /* Map of param-name → scalar type. Defines the shape of `groups[].params`. Example: `{ headline: 'string', show_cta: 'bool' }`. */
    @Json(name = "params")
    val params: UpdateExperimentRequest.Params? = null,

    /* Replacement groups. Weights must sum to 10000. Immutable while running. */
    @Json(name = "groups")
    val groups: kotlin.collections.List<ListExperimentsResponseDataInnerGroupsInner>? = null,

    @Json(name = "significance_threshold")
    val significanceThreshold: java.math.BigDecimal? = null,

    @Json(name = "min_runtime_days")
    val minRuntimeDays: kotlin.Int? = null,

    @Json(name = "min_sample_size")
    val minSampleSize: kotlin.Int? = null,

    @Json(name = "sequential_testing")
    val sequentialTesting: kotlin.Boolean? = null,

    /* Replaces the goal metric — DSL `query` or `event` (+`aggregation`/`value`) the server compiles (event auto-upserted). */
    @Json(name = "goal_metric")
    val goalMetric: ExperimentInlineMetric? = null,

    /* Replaces the guardrail set wholesale (event auto-upserted per entry). */
    @Json(name = "guardrail_metrics")
    val guardrailMetrics: kotlin.collections.List<ExperimentInlineMetric>? = null

) {

    /**
     * Map of param-name → scalar type. Defines the shape of `groups[].params`. Example: `{ headline: 'string', show_cta: 'bool' }`.
     *
     * Values: string,bool,number
     */
    @JsonClass(generateAdapter = false)
    enum class Params(val value: kotlin.String) {
        @Json(name = "string") string("string"),
        @Json(name = "bool") bool("bool"),
        @Json(name = "number") number("number");
    }

}

