/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListEventsResponseInnerPropertiesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `PATCH /api/admin/events/{id}` and `POST /api/admin/events/{id}/approve`. All fields optional; `name` is immutable after create.
 *
 * @param folder Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
 * @param description New description for the event.
 * @param properties Replaces the full property set (no merge). Omit to leave properties unchanged.
 */


data class ApproveEventRequest (

    /* Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    @Json(name = "folder")
    val folder: kotlin.String? = null,

    /* New description for the event. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Replaces the full property set (no merge). Omit to leave properties unchanged. */
    @Json(name = "properties")
    val properties: kotlin.collections.List<ListEventsResponseInnerPropertiesInner>? = null

) {


}

