/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Non-secret config for a Claude trigger.
 *
 * @param routineId The Claude Code routine id this connector fires (the id recorded at setup). Idempotency key for the connector.
 * @param fireText Optional default prompt sent on a manual fire / when no event text applies.
 */


data class ClaudeTriggerConfig (

    /* The Claude Code routine id this connector fires (the id recorded at setup). Idempotency key for the connector. */
    @Json(name = "routineId")
    val routineId: kotlin.String,

    /* Optional default prompt sent on a manual fire / when no event text applies. */
    @Json(name = "fireText")
    val fireText: kotlin.String? = null

) {


}

