/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Non-secret config for a Copilot trigger.
 *
 * @param owner GitHub repo owner. Together with `repo` forms the connector's idempotency key (`owner/repo`).
 * @param repo GitHub repo name.
 * @param projectId Shipeasy project id the run targets.
 * @param baseRef Optional base ref the agent branches from.
 */


data class CopilotTriggerConfig (

    /* GitHub repo owner. Together with `repo` forms the connector's idempotency key (`owner/repo`). */
    @Json(name = "owner")
    val owner: kotlin.String,

    /* GitHub repo name. */
    @Json(name = "repo")
    val repo: kotlin.String,

    /* Shipeasy project id the run targets. */
    @Json(name = "projectId")
    val projectId: kotlin.String,

    /* Optional base ref the agent branches from. */
    @Json(name = "baseRef")
    val baseRef: kotlin.String? = null

) {


}

