/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ExperimentInlineMetric
import ai.shipeasy.admin.models.ListExperimentsResponseDataInnerGroupsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/experiments`. `name`, `universe`, and `groups` (≥2, weights sum to 10000) required.
 *
 * @param name Stable experiment key. Single segment or `folder.name` (a-z, 0-9, `_`/`-`; max 128 chars). Used by SDKs as `Shipeasy.getExperiment(user, '<name>')`. Immutable after create.
 * @param universe Name of an existing universe in the project. Returns `422` if the universe doesn't exist.
 * @param groups Two or more variants. Weights must sum to exactly 10000 (100%). Immutable while running.
 * @param description Free-form description. Max 2000 chars, markdown rendered in the dashboard.
 * @param hypothesis Hypothesis statement shown in the editor. Display-only.
 * @param tag Short tag chip rendered next to the name. Display-only.
 * @param ownerEmail Owner email. Display-only.
 * @param audience Audience label shown in the editor. Display-only.
 * @param bucketBy User-attribute name used as the bucketing key — e.g. `user_id` (default), `session_id`, `device_id`, or a custom attribute like `company_id` to keep a whole org on one variant. Defaults to `user_id` when omitted.
 * @param folder Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
 * @param targetingGate Optional gate name. Only callers that pass the gate are enrolled in the experiment.
 * @param allocationPct Share of the (gated) audience allocated to the experiment, in basis points (0–10000 = 0%–100%). `0` = unallocated. Use `allocation_percent` (0–100) below to think in percent. Immutable while the experiment is running.
 * @param allocationPercent Allocation as a **percentage** (0–100, fractional ok). Friendlier alias for `allocation_pct`; converted to basis points server-side (e.g. `50` = 5000 bp). If both are set, `allocation_percent` wins.
 * @param salt Hash salt for bucketing. Auto-generated if omitted. Immutable while running.
 * @param params Map of param-name → scalar type. Defines the shape of `groups[].params`. Example: `{ headline: 'string', show_cta: 'bool' }`.
 * @param significanceThreshold p-value cutoff used by the analysis pass. Defaults to `0.05`. Values other than 0.05 require Pro plan or higher.
 * @param minRuntimeDays Minimum days the experiment must run before results are considered conclusive.
 * @param minSampleSize Minimum exposures per group before results are considered conclusive.
 * @param sequentialTesting Enable sequential testing (always-valid p-values). Requires Premium plan or higher.
 * @param goalMetric Single goal metric defined inline — either a DSL `query` or an `event` (+`aggregation`/`value`) the server compiles. Attaching one is required before the experiment can be started. The underlying event is auto-created if missing.
 * @param guardrailMetrics Up to 10 guardrail metrics defined inline. Each is upserted (event + metric) and attached with role=guardrail.
 */


data class CreateExperimentRequest (

    /* Stable experiment key. Single segment or `folder.name` (a-z, 0-9, `_`/`-`; max 128 chars). Used by SDKs as `Shipeasy.getExperiment(user, '<name>')`. Immutable after create. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Name of an existing universe in the project. Returns `422` if the universe doesn't exist. */
    @Json(name = "universe")
    val universe: kotlin.String,

    /* Two or more variants. Weights must sum to exactly 10000 (100%). Immutable while running. */
    @Json(name = "groups")
    val groups: kotlin.collections.List<ListExperimentsResponseDataInnerGroupsInner>,

    /* Free-form description. Max 2000 chars, markdown rendered in the dashboard. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Hypothesis statement shown in the editor. Display-only. */
    @Json(name = "hypothesis")
    val hypothesis: kotlin.String? = null,

    /* Short tag chip rendered next to the name. Display-only. */
    @Json(name = "tag")
    val tag: kotlin.String? = null,

    /* Owner email. Display-only. */
    @Json(name = "owner_email")
    val ownerEmail: kotlin.String? = null,

    /* Audience label shown in the editor. Display-only. */
    @Json(name = "audience")
    val audience: kotlin.String? = null,

    /* User-attribute name used as the bucketing key — e.g. `user_id` (default), `session_id`, `device_id`, or a custom attribute like `company_id` to keep a whole org on one variant. Defaults to `user_id` when omitted. */
    @Json(name = "bucket_by")
    val bucketBy: kotlin.String? = null,

    /* Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    @Json(name = "folder")
    val folder: kotlin.String? = null,

    /* Optional gate name. Only callers that pass the gate are enrolled in the experiment. */
    @Json(name = "targeting_gate")
    val targetingGate: kotlin.String? = null,

    /* Share of the (gated) audience allocated to the experiment, in basis points (0–10000 = 0%–100%). `0` = unallocated. Use `allocation_percent` (0–100) below to think in percent. Immutable while the experiment is running. */
    @Json(name = "allocation_pct")
    val allocationPct: kotlin.Int? = 0,

    /* Allocation as a **percentage** (0–100, fractional ok). Friendlier alias for `allocation_pct`; converted to basis points server-side (e.g. `50` = 5000 bp). If both are set, `allocation_percent` wins. */
    @Json(name = "allocation_percent")
    val allocationPercent: java.math.BigDecimal? = null,

    /* Hash salt for bucketing. Auto-generated if omitted. Immutable while running. */
    @Json(name = "salt")
    val salt: kotlin.String? = null,

    /* Map of param-name → scalar type. Defines the shape of `groups[].params`. Example: `{ headline: 'string', show_cta: 'bool' }`. */
    @Json(name = "params")
    val params: CreateExperimentRequest.Params? = null,

    /* p-value cutoff used by the analysis pass. Defaults to `0.05`. Values other than 0.05 require Pro plan or higher. */
    @Json(name = "significance_threshold")
    val significanceThreshold: java.math.BigDecimal? = java.math.BigDecimal("0.05"),

    /* Minimum days the experiment must run before results are considered conclusive. */
    @Json(name = "min_runtime_days")
    val minRuntimeDays: kotlin.Int? = 0,

    /* Minimum exposures per group before results are considered conclusive. */
    @Json(name = "min_sample_size")
    val minSampleSize: kotlin.Int? = 100,

    /* Enable sequential testing (always-valid p-values). Requires Premium plan or higher. */
    @Json(name = "sequential_testing")
    val sequentialTesting: kotlin.Boolean? = false,

    /* Single goal metric defined inline — either a DSL `query` or an `event` (+`aggregation`/`value`) the server compiles. Attaching one is required before the experiment can be started. The underlying event is auto-created if missing. */
    @Json(name = "goal_metric")
    val goalMetric: ExperimentInlineMetric? = null,

    /* Up to 10 guardrail metrics defined inline. Each is upserted (event + metric) and attached with role=guardrail. */
    @Json(name = "guardrail_metrics")
    val guardrailMetrics: kotlin.collections.List<ExperimentInlineMetric>? = null

) {

    /**
     * Map of param-name → scalar type. Defines the shape of `groups[].params`. Example: `{ headline: 'string', show_cta: 'bool' }`.
     *
     * Values: string,bool,number
     */
    @JsonClass(generateAdapter = false)
    enum class Params(val value: kotlin.String) {
        @Json(name = "string") string("string"),
        @Json(name = "bool") bool("bool"),
        @Json(name = "number") number("number");
    }

}

