/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.GateTemplateRule

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/gate-templates`. Creates a per-project (customer) template. At minimum supply `name` + `rules`.
 *
 * @param name Human label. Unique per project.
 * @param rules The rule definition captured by the template.
 * @param description One-liner shown in pickers and matched by the list `query` filter.
 * @param category 
 * @param iconKey Display-only icon hint.
 * @param auto Mark the attribute as request-derived (resolved at the SDK edge).
 */


data class CreateGateTemplateRequest (

    /* Human label. Unique per project. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The rule definition captured by the template. */
    @Json(name = "rules")
    val rules: kotlin.collections.List<GateTemplateRule>,

    /* One-liner shown in pickers and matched by the list `query` filter. */
    @Json(name = "description")
    val description: kotlin.String? = "",

    @Json(name = "category")
    val category: CreateGateTemplateRequest.Category? = Category.condition,

    /* Display-only icon hint. */
    @Json(name = "icon_key")
    val iconKey: kotlin.String? = null,

    /* Mark the attribute as request-derived (resolved at the SDK edge). */
    @Json(name = "auto")
    val auto: kotlin.Boolean? = false

) {

    /**
     * 
     *
     * Values: condition,rollout
     */
    @JsonClass(generateAdapter = false)
    enum class Category(val value: kotlin.String) {
        @Json(name = "condition") condition("condition"),
        @Json(name = "rollout") rollout("rollout");
    }

}

