/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/killswitches`. Only `name` is required.
 *
 * @param name Stable config/killswitch key in `folder.name` form (two lowercase segments separated by a dot, e.g. `pricing.tiers`). Immutable after create.
 * @param description Optional free-form description shown in the dashboard. Max 512 chars.
 * @param folder Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
 * @param `value` Default value applied to every env at creation. Defaults to `false`. Use `true` to ship the killswitch pre-tripped.
 * @param switches Initial per-switch overrides applied to every env. Empty/omitted leaves the killswitch with only the flat `value`.
 */


data class CreateKillswitchRequest (

    /* Stable config/killswitch key in `folder.name` form (two lowercase segments separated by a dot, e.g. `pricing.tiers`). Immutable after create. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Optional free-form description shown in the dashboard. Max 512 chars. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    @Json(name = "folder")
    val folder: kotlin.String? = null,

    /* Default value applied to every env at creation. Defaults to `false`. Use `true` to ship the killswitch pre-tripped. */
    @Json(name = "value")
    val `value`: kotlin.Boolean? = null,

    /* Initial per-switch overrides applied to every env. Empty/omitted leaves the killswitch with only the flat `value`. */
    @Json(name = "switches")
    val switches: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null

) {


}

