/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Result of a successful metric create.
 *
 * @param id Newly assigned metric id.
 * @param name Metric name that was created.
 */


data class CreateMetricResponse (

    /* Newly assigned metric id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Metric name that was created. */
    @Json(name = "name")
    val name: kotlin.String

) {


}

