/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Response for `POST /api/admin/ops`.
 *
 * @param id Newly created item id.
 * @param number Per-project item number assigned to the new item.
 */


data class CreateOpsItemResponse (

    /* Newly created item id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Per-project item number assigned to the new item. */
    @Json(name = "number")
    val number: java.math.BigDecimal? = null

) {


}

