/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Result of creating (or approving an existing pending) event.
 *
 * @param id Newly assigned event id.
 * @param name The event name that was registered.
 */


data class CreateEventResponse (

    /* Newly assigned event id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The event name that was registered. */
    @Json(name = "name")
    val name: kotlin.String

) {


}

