/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/keys`. Only `type` is required.  `env` is **required** for `server` and `client` keys (the key is bound to one environment — that binding is the read-env isolation boundary). For `admin` and `ops` keys `env` is ignored and the key is pinned to `prod`.
 *
 * @param type Key kind to mint. `server` (back-end), `client` (public, browser), `admin` (CLI/devtools token), `ops` (restricted unattended-trigger credential). `admin`/`ops` keys don't count toward the plan key limit.
 * @param env Environment to bind the key to. Always required. For `server`/`client` keys it is the isolation boundary the worker reads from; `admin`/`ops` keys are env-agnostic and pinned to `prod` by the handler regardless of the value sent.
 * @param name Optional human label. Programmatic (API) mints that omit it get an auto-generated descriptive name; dashboard mints may leave it blank.
 * @param scopes Optional permission strings recorded on the key. `tickets:public_create` is enforced: a client key needs it (plus the project's `allowPublicTickets` setting) to file a `pending_approval` bug via the public `POST /cli/report` endpoint. The rest are audit/display only.
 * @param expiresInDays Days until the key expires (1–3650), or `null`/omitted for a key that never expires. Ignored for `admin` keys (fixed 90-day expiry) and `ops` keys (short sliding window).
 */


data class CreateKeyRequest (

    /* Key kind to mint. `server` (back-end), `client` (public, browser), `admin` (CLI/devtools token), `ops` (restricted unattended-trigger credential). `admin`/`ops` keys don't count toward the plan key limit. */
    @Json(name = "type")
    val type: CreateKeyRequest.Type,

    /* Environment to bind the key to. Always required. For `server`/`client` keys it is the isolation boundary the worker reads from; `admin`/`ops` keys are env-agnostic and pinned to `prod` by the handler regardless of the value sent. */
    @Json(name = "env")
    val env: CreateKeyRequest.Env,

    /* Optional human label. Programmatic (API) mints that omit it get an auto-generated descriptive name; dashboard mints may leave it blank. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Optional permission strings recorded on the key. `tickets:public_create` is enforced: a client key needs it (plus the project's `allowPublicTickets` setting) to file a `pending_approval` bug via the public `POST /cli/report` endpoint. The rest are audit/display only. */
    @Json(name = "scopes")
    val scopes: kotlin.collections.List<CreateKeyRequest.Scopes>? = null,

    /* Days until the key expires (1–3650), or `null`/omitted for a key that never expires. Ignored for `admin` keys (fixed 90-day expiry) and `ops` keys (short sliding window). */
    @Json(name = "expiresInDays")
    val expiresInDays: kotlin.Int? = null

) {

    /**
     * Key kind to mint. `server` (back-end), `client` (public, browser), `admin` (CLI/devtools token), `ops` (restricted unattended-trigger credential). `admin`/`ops` keys don't count toward the plan key limit.
     *
     * Values: server,client,admin,ops
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "server") server("server"),
        @Json(name = "client") client("client"),
        @Json(name = "admin") admin("admin"),
        @Json(name = "ops") ops("ops");
    }
    /**
     * Environment to bind the key to. Always required. For `server`/`client` keys it is the isolation boundary the worker reads from; `admin`/`ops` keys are env-agnostic and pinned to `prod` by the handler regardless of the value sent.
     *
     * Values: dev,staging,prod
     */
    @JsonClass(generateAdapter = false)
    enum class Env(val value: kotlin.String) {
        @Json(name = "dev") dev("dev"),
        @Json(name = "staging") staging("staging"),
        @Json(name = "prod") prod("prod");
    }
    /**
     * Optional permission strings recorded on the key. `tickets:public_create` is enforced: a client key needs it (plus the project's `allowPublicTickets` setting) to file a `pending_approval` bug via the public `POST /cli/report` endpoint. The rest are audit/display only.
     *
     * Values: experimentsColonRead,gatesColonEvaluate,eventsColonWrite,configsColonWrite,experimentsColonWrite,ticketsColonPublic_create
     */
    @JsonClass(generateAdapter = false)
    enum class Scopes(val value: kotlin.String) {
        @Json(name = "experiments:read") experimentsColonRead("experiments:read"),
        @Json(name = "gates:evaluate") gatesColonEvaluate("gates:evaluate"),
        @Json(name = "events:write") eventsColonWrite("events:write"),
        @Json(name = "configs:write") configsColonWrite("configs:write"),
        @Json(name = "experiments:write") experimentsColonWrite("experiments:write"),
        @Json(name = "tickets:public_create") ticketsColonPublic_create("tickets:public_create");
    }

}

