/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/i18n/drafts`. Stages a new translation draft against a target profile, optionally seeding from a source profile.
 *
 * @param name Draft name, e.g. the target locale being staged.
 * @param profileId Profile the draft targets.
 * @param sourceProfileId Optional profile to seed the draft's keys from.
 */


data class CreateI18nDraftRequest (

    /* Draft name, e.g. the target locale being staged. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Profile the draft targets. */
    @Json(name = "profile_id")
    val profileId: java.util.UUID,

    /* Optional profile to seed the draft's keys from. */
    @Json(name = "source_profile_id")
    val sourceProfileId: java.util.UUID? = null

) {


}

