/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Response for `POST /api/admin/ops/{handle}/comments`.
 *
 * @param id Newly created comment id.
 */


data class CreateOpsCommentResponse (

    /* Newly created comment id. */
    @Json(name = "id")
    val id: kotlin.String

) {


}

