/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Non-secret config for a Cursor trigger.
 *
 * @param repoUrl Repo the cloud agent runs against, e.g. `https://github.com/owner/repo`. Idempotency key for the connector.
 * @param projectId Shipeasy project id the run targets.
 * @param startingRef Optional git ref the run starts from.
 */


data class CursorTriggerConfig (

    /* Repo the cloud agent runs against, e.g. `https://github.com/owner/repo`. Idempotency key for the connector. */
    @Json(name = "repoUrl")
    val repoUrl: java.net.URI,

    /* Shipeasy project id the run targets. */
    @Json(name = "projectId")
    val projectId: kotlin.String,

    /* Optional git ref the run starts from. */
    @Json(name = "startingRef")
    val startingRef: kotlin.String? = null

) {


}

