/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ErrorSeriesResponseRowsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Bucketed occurrence counts for one tracked error (by its fingerprint), plus the Analytics Engine SQL that produced them.
 *
 * @param sql The Analytics Engine SQL executed to produce `rows` (echoed for transparency / debugging).
 * @param rows Bucketed occurrence series, ordered by `t` ascending.
 */


data class ErrorSeriesResponse (

    /* The Analytics Engine SQL executed to produce `rows` (echoed for transparency / debugging). */
    @Json(name = "sql")
    val sql: kotlin.String,

    /* Bucketed occurrence series, ordered by `t` ascending. */
    @Json(name = "rows")
    val rows: kotlin.collections.List<ErrorSeriesResponseRowsInner>

) {


}

