/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Inline metric — a DSL `query`, or an `event` (+ `aggregation`/`value`) the server compiles into one.
 *
 * @param name Stable metric key. Single segment or `folder.name`; lowercase letters, digits, `_`/`-`; max 128 chars.
 * @param query Metric DSL string. Provide this OR `event`.
 * @param event Event name to build the metric from server-side. Auto-created if missing.
 * @param aggregation Reducer for the `event` form. Defaults to `count_users`.
 * @param `value` Numeric event property for `sum`/`avg` (with `event`).
 * @param minEffectOfInterest Per-experiment override of the metric's default minimum effect of interest (relative, 0–1) — the smallest change worth acting on for this experiment's decision. `null`/omitted inherits the metric default. For a guardrail, the non-inferiority margin.
 */


data class ExperimentInlineMetric (

    /* Stable metric key. Single segment or `folder.name`; lowercase letters, digits, `_`/`-`; max 128 chars. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Metric DSL string. Provide this OR `event`. */
    @Json(name = "query")
    val query: kotlin.String? = null,

    /* Event name to build the metric from server-side. Auto-created if missing. */
    @Json(name = "event")
    val event: kotlin.String? = null,

    /* Reducer for the `event` form. Defaults to `count_users`. */
    @Json(name = "aggregation")
    val aggregation: ExperimentInlineMetric.Aggregation? = null,

    /* Numeric event property for `sum`/`avg` (with `event`). */
    @Json(name = "value")
    val `value`: kotlin.String? = null,

    /* Per-experiment override of the metric's default minimum effect of interest (relative, 0–1) — the smallest change worth acting on for this experiment's decision. `null`/omitted inherits the metric default. For a guardrail, the non-inferiority margin. */
    @Json(name = "min_effect_of_interest")
    val minEffectOfInterest: java.math.BigDecimal? = null

) {

    /**
     * Reducer for the `event` form. Defaults to `count_users`.
     *
     * Values: count_users,count_events,retention_7d,retention_30d,sum,avg
     */
    @JsonClass(generateAdapter = false)
    enum class Aggregation(val value: kotlin.String) {
        @Json(name = "count_users") count_users("count_users"),
        @Json(name = "count_events") count_events("count_events"),
        @Json(name = "retention_7d") retention_7d("retention_7d"),
        @Json(name = "retention_30d") retention_30d("retention_30d"),
        @Json(name = "sum") sum("sum"),
        @Json(name = "avg") avg("avg");
    }

}

