/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Single targeting predicate as returned by the API. `value` is optional here — read-only built-in templates (e.g. `@owner`, or presets whose operand is supplied at substitution time) legitimately omit it. Request bodies still require `value`.
 *
 * @param attr Attribute key on the evaluation context (e.g. `country`, `plan`, `email`). Matched case-sensitively against `Shipeasy.checkGate(user, name)` input. May be empty on a built-in template whose attribute is supplied at substitution time (e.g. the `exp_in` \"in any experiment\" preset — you fill in the experiment name).
 * @param op Comparison operator. Equality: `eq`/`neq`. Set membership: `in`/`not_in` (value is an array). Numeric order: `gt`/`gte`/`lt`/`lte`. Semver order: `semver_gt`/`semver_gte`/`semver_lt`/`semver_lte`. String: `contains` (substring), `regex` (JS-flavour pattern). Cross-resource: `gate_pass` (value is another gate's name), `exp_in` (attr is an experiment name, value is a variant / `\"$holdout\"` / `\"$any\"`).
 * @param `value` 
 */


data class GateTemplateRuleResponse (

    /* Attribute key on the evaluation context (e.g. `country`, `plan`, `email`). Matched case-sensitively against `Shipeasy.checkGate(user, name)` input. May be empty on a built-in template whose attribute is supplied at substitution time (e.g. the `exp_in` \"in any experiment\" preset — you fill in the experiment name). */
    @Json(name = "attr")
    val attr: kotlin.String,

    /* Comparison operator. Equality: `eq`/`neq`. Set membership: `in`/`not_in` (value is an array). Numeric order: `gt`/`gte`/`lt`/`lte`. Semver order: `semver_gt`/`semver_gte`/`semver_lt`/`semver_lte`. String: `contains` (substring), `regex` (JS-flavour pattern). Cross-resource: `gate_pass` (value is another gate's name), `exp_in` (attr is an experiment name, value is a variant / `\"$holdout\"` / `\"$any\"`). */
    @Json(name = "op")
    val op: GateTemplateRuleResponse.Op,

    @Json(name = "value")
    val `value`: kotlin.Any? = null

) {

    /**
     * Comparison operator. Equality: `eq`/`neq`. Set membership: `in`/`not_in` (value is an array). Numeric order: `gt`/`gte`/`lt`/`lte`. Semver order: `semver_gt`/`semver_gte`/`semver_lt`/`semver_lte`. String: `contains` (substring), `regex` (JS-flavour pattern). Cross-resource: `gate_pass` (value is another gate's name), `exp_in` (attr is an experiment name, value is a variant / `\"$holdout\"` / `\"$any\"`).
     *
     * Values: eq,neq,`in`,not_in,gt,gte,lt,lte,contains,regex,semver_gt,semver_gte,semver_lt,semver_lte,gate_pass,exp_in
     */
    @JsonClass(generateAdapter = false)
    enum class Op(val value: kotlin.String) {
        @Json(name = "eq") eq("eq"),
        @Json(name = "neq") neq("neq"),
        @Json(name = "in") `in`("in"),
        @Json(name = "not_in") not_in("not_in"),
        @Json(name = "gt") gt("gt"),
        @Json(name = "gte") gte("gte"),
        @Json(name = "lt") lt("lt"),
        @Json(name = "lte") lte("lte"),
        @Json(name = "contains") contains("contains"),
        @Json(name = "regex") regex("regex"),
        @Json(name = "semver_gt") semver_gt("semver_gt"),
        @Json(name = "semver_gte") semver_gte("semver_gte"),
        @Json(name = "semver_lt") semver_lt("semver_lt"),
        @Json(name = "semver_lte") semver_lte("semver_lte"),
        @Json(name = "gate_pass") gate_pass("gate_pass"),
        @Json(name = "exp_in") exp_in("exp_in");
    }

}

