/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListExperimentsResponseDataInnerGroupsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Stable opaque experiment id (`exp_…`).
 * @param name Stable experiment key. Single segment or `folder.name` (a-z, 0-9, `_`/`-`; max 128 chars). Used by SDKs as `Shipeasy.getExperiment(user, '<name>')`. Immutable after create.
 * @param description 
 * @param hypothesis 
 * @param tag 
 * @param ownerEmail 
 * @param audience 
 * @param bucketBy User-attribute name used as the bucketing key — e.g. `user_id` (default), `session_id`, `device_id`, or a custom attribute like `company_id` to keep a whole org on one variant. Defaults to `user_id` when omitted.
 * @param folder 
 * @param status 
 * @param universe Universe name this experiment draws from.
 * @param targetingGate 
 * @param allocationPct Allocation in basis points (0–10000).
 * @param salt 
 * @param params 
 * @param groups 
 * @param significanceThreshold 
 * @param minRuntimeDays 
 * @param minSampleSize 
 * @param sequentialTesting 
 * @param startedAt ISO-8601 timestamp the experiment last transitioned to `running`, or `null`.
 * @param updatedAt 
 * @param stoppedAt 
 */


data class GetExperimentResponse (

    /* Stable opaque experiment id (`exp_…`). */
    @Json(name = "id")
    val id: kotlin.String,

    /* Stable experiment key. Single segment or `folder.name` (a-z, 0-9, `_`/`-`; max 128 chars). Used by SDKs as `Shipeasy.getExperiment(user, '<name>')`. Immutable after create. */
    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String?,

    @Json(name = "hypothesis")
    val hypothesis: kotlin.String?,

    @Json(name = "tag")
    val tag: kotlin.String?,

    @Json(name = "ownerEmail")
    val ownerEmail: kotlin.String?,

    @Json(name = "audience")
    val audience: kotlin.String?,

    /* User-attribute name used as the bucketing key — e.g. `user_id` (default), `session_id`, `device_id`, or a custom attribute like `company_id` to keep a whole org on one variant. Defaults to `user_id` when omitted. */
    @Json(name = "bucketBy")
    val bucketBy: kotlin.String?,

    @Json(name = "folder")
    val folder: kotlin.String?,

    @Json(name = "status")
    val status: GetExperimentResponse.Status,

    /* Universe name this experiment draws from. */
    @Json(name = "universe")
    val universe: kotlin.String,

    @Json(name = "targetingGate")
    val targetingGate: kotlin.String?,

    /* Allocation in basis points (0–10000). */
    @Json(name = "allocationPct")
    val allocationPct: kotlin.Int,

    @Json(name = "salt")
    val salt: kotlin.String,

    @Json(name = "params")
    val params: GetExperimentResponse.Params,

    @Json(name = "groups")
    val groups: kotlin.collections.List<ListExperimentsResponseDataInnerGroupsInner>,

    @Json(name = "significanceThreshold")
    val significanceThreshold: java.math.BigDecimal,

    @Json(name = "minRuntimeDays")
    val minRuntimeDays: kotlin.Int,

    @Json(name = "minSampleSize")
    val minSampleSize: kotlin.Int,

    @Json(name = "sequentialTesting")
    val sequentialTesting: kotlin.Boolean,

    /* ISO-8601 timestamp the experiment last transitioned to `running`, or `null`. */
    @Json(name = "startedAt")
    val startedAt: kotlin.String?,

    @Json(name = "updatedAt")
    val updatedAt: kotlin.String,

    @Json(name = "stoppedAt")
    val stoppedAt: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: draft,running,stopped,archived
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "draft") draft("draft"),
        @Json(name = "running") running("running"),
        @Json(name = "stopped") stopped("stopped"),
        @Json(name = "archived") archived("archived");
    }
    /**
     * 
     *
     * Values: string,bool,number
     */
    @JsonClass(generateAdapter = false)
    enum class Params(val value: kotlin.String) {
        @Json(name = "string") string("string"),
        @Json(name = "bool") bool("bool"),
        @Json(name = "number") number("number");
    }

}

