/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The GitHub issue this item opened.
 *
 * @param number GitHub issue number.
 * @param url HTML URL of the opened issue.
 * @param owner Repository owner (org or user).
 * @param repo Repository name.
 * @param createdAt ISO-8601 timestamp the issue was opened.
 */


data class GithubConnectorDataIssue (

    /* GitHub issue number. */
    @Json(name = "number")
    val number: java.math.BigDecimal,

    /* HTML URL of the opened issue. */
    @Json(name = "url")
    val url: kotlin.String,

    /* Repository owner (org or user). */
    @Json(name = "owner")
    val owner: kotlin.String,

    /* Repository name. */
    @Json(name = "repo")
    val repo: kotlin.String,

    /* ISO-8601 timestamp the issue was opened. */
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

