/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Runtime killswitch payload returned to SDKs.
 *
 * @param `value` Default boolean delivered when no `switches` entry matches.
 * @param switches Per-switch overrides; a matching key takes precedence over `value`.
 */


data class KillswitchValue (

    /* Default boolean delivered when no `switches` entry matches. */
    @Json(name = "value")
    val `value`: kotlin.Boolean,

    /* Per-switch overrides; a matching key takes precedence over `value`. */
    @Json(name = "switches")
    val switches: kotlin.collections.Map<kotlin.String, kotlin.Boolean>? = null

) {


}

