/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/ops/{handle}/link-pr`.
 *
 * @param prNumber PR number to record on the item. `null` unlinks the PR.
 * @param prUrl Explicit PR URL. Required for error/alert tickets (no GitHub issue to derive the URL from).
 */


data class LinkPrToOpsItemRequest (

    /* PR number to record on the item. `null` unlinks the PR. */
    @Json(name = "prNumber")
    val prNumber: kotlin.Int?,

    /* Explicit PR URL. Required for error/alert tickets (no GitHub issue to derive the URL from). */
    @Json(name = "prUrl")
    val prUrl: java.net.URI? = null

) {


}

