/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListGatesResponseDataInnerRulesInner
import ai.shipeasy.admin.models.ListGatesResponseDataInnerStackInnerOneOfRamp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Rule-based sub-gate. When the rules match and the caller falls in the per-condition rollout bucket, evaluation short-circuits and the gate returns `true`; otherwise it falls through to the next entry.
 *
 * @param id Client-supplied stable id for the stack entry (used for React keys, audit diffs, and as the default per-condition rollout salt).
 * @param type Discriminator. `condition` = rule-based predicate sub-gate.
 * @param name Human label shown in the dashboard.
 * @param fromTemplate Id of the project template this entry was seeded from, or `null` if hand-authored.
 * @param pass Combinator across `rules`. `all` = AND (default), `any` = OR.
 * @param rules Predicates evaluated under `pass`. Empty array = match nothing.
 * @param rolloutPct Per-condition rollout in basis points. After the rules match, the caller is bucketed at this %; in-bucket → gate `true`, otherwise fall through to the next entry. Absent ⇒ 10000 (100%, every matching caller passes).
 * @param bucketBy Attribute used to hash the caller into the per-condition bucket. Default `userID`.
 * @param salt Per-condition hash salt. Defaults to the entry `id`, then the gate salt.
 * @param ramp 
 * @param locked If `true`, dashboard hides edit controls (e.g. the trailing public-floor entry).
 */


data class ListGatesResponseDataInnerStackInnerOneOf (

    /* Client-supplied stable id for the stack entry (used for React keys, audit diffs, and as the default per-condition rollout salt). */
    @Json(name = "id")
    val id: kotlin.String,

    /* Discriminator. `condition` = rule-based predicate sub-gate. */
    @Json(name = "type")
    val type: ListGatesResponseDataInnerStackInnerOneOf.Type,

    /* Human label shown in the dashboard. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Id of the project template this entry was seeded from, or `null` if hand-authored. */
    @Json(name = "fromTemplate")
    val fromTemplate: kotlin.String? = null,

    /* Combinator across `rules`. `all` = AND (default), `any` = OR. */
    @Json(name = "pass")
    val pass: ListGatesResponseDataInnerStackInnerOneOf.Pass? = null,

    /* Predicates evaluated under `pass`. Empty array = match nothing. */
    @Json(name = "rules")
    val rules: kotlin.collections.List<ListGatesResponseDataInnerRulesInner>? = null,

    /* Per-condition rollout in basis points. After the rules match, the caller is bucketed at this %; in-bucket → gate `true`, otherwise fall through to the next entry. Absent ⇒ 10000 (100%, every matching caller passes). */
    @Json(name = "rolloutPct")
    val rolloutPct: kotlin.Int? = null,

    /* Attribute used to hash the caller into the per-condition bucket. Default `userID`. */
    @Json(name = "bucketBy")
    val bucketBy: kotlin.String? = null,

    /* Per-condition hash salt. Defaults to the entry `id`, then the gate salt. */
    @Json(name = "salt")
    val salt: kotlin.String? = null,

    @Json(name = "ramp")
    val ramp: ListGatesResponseDataInnerStackInnerOneOfRamp? = null,

    /* If `true`, dashboard hides edit controls (e.g. the trailing public-floor entry). */
    @Json(name = "locked")
    val locked: kotlin.Boolean? = null

) {

    /**
     * Discriminator. `condition` = rule-based predicate sub-gate.
     *
     * Values: condition
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "condition") condition("condition");
    }
    /**
     * Combinator across `rules`. `all` = AND (default), `any` = OR.
     *
     * Values: all,any
     */
    @JsonClass(generateAdapter = false)
    enum class Pass(val value: kotlin.String) {
        @Json(name = "all") all("all"),
        @Json(name = "any") any("any");
    }

}

