/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Master switch. Returned as `1`/`0` from D1; treat truthy as enabled.
 *
 */


class ListGatesResponseDataInnerEnabled (

) {


}

