/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.OpsComment

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Response for `GET /api/admin/ops/{handle}/comments` — the thread, oldest first.
 *
 * @param comments 
 */


data class ListOpsCommentsResponse (

    @Json(name = "comments")
    val comments: kotlin.collections.List<OpsComment>

) {


}

