/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Stable opaque universe id.
 * @param name Stable universe key. Single segment or `folder.name`. Lowercase letters, digits, `_` or `-`; max 128 chars. Immutable after create.
 * @param unitType Unit of randomisation. Snake-case in request (`unit_type`), camelCase in response.
 * @param holdoutRange Reserved holdout bucket range, or `null` if none.
 * @param createdAt ISO-8601 timestamp of creation.
 */


data class ListUniversesResponseDataInner (

    /* Stable opaque universe id. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Stable universe key. Single segment or `folder.name`. Lowercase letters, digits, `_` or `-`; max 128 chars. Immutable after create. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Unit of randomisation. Snake-case in request (`unit_type`), camelCase in response. */
    @Json(name = "unitType")
    val unitType: kotlin.String,

    /* Reserved holdout bucket range, or `null` if none. */
    @Json(name = "holdoutRange")
    val holdoutRange: kotlin.collections.List<java.math.BigDecimal>?,

    /* ISO-8601 timestamp of creation. */
    @Json(name = "createdAt")
    val createdAt: kotlin.String

) {


}

