/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ListConfigsResponseDataInnerDraftsValue
import ai.shipeasy.admin.models.ListConfigsResponseDataInnerEnvsValue

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Stable opaque config id (`cfg_…`).
 * @param name Stable config key in `folder.name` form (two lowercase segments separated by a dot, e.g. `pricing.tiers`). Used by SDKs as `Shipeasy.getConfig('<name>')`. Immutable after create.
 * @param description 
 * @param schema JSON Schema (draft 2020-12) describing the shape of the config value. Top-level `type` must be `'object'`; every published value is validated against this schema.
 * @param updatedAt ISO-8601 timestamp of last mutation.
 * @param envs Per-env latest published version metadata.
 * @param drafts Per-env active drafts (if any).
 * @param propertyValues Per-env latest published values (only returned by `GET /{id}`, not list).
 * @param draftValues Per-env draft values (only returned by `GET /{id}`).
 */


data class ListConfigsResponseDataInner (

    /* Stable opaque config id (`cfg_…`). */
    @Json(name = "id")
    val id: kotlin.String,

    /* Stable config key in `folder.name` form (two lowercase segments separated by a dot, e.g. `pricing.tiers`). Used by SDKs as `Shipeasy.getConfig('<name>')`. Immutable after create. */
    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String?,

    /* JSON Schema (draft 2020-12) describing the shape of the config value. Top-level `type` must be `'object'`; every published value is validated against this schema. */
    @Json(name = "schema")
    val schema: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* ISO-8601 timestamp of last mutation. */
    @Json(name = "updatedAt")
    val updatedAt: kotlin.String,

    /* Per-env latest published version metadata. */
    @Json(name = "envs")
    val envs: kotlin.collections.Map<kotlin.String, ListConfigsResponseDataInnerEnvsValue>,

    /* Per-env active drafts (if any). */
    @Json(name = "drafts")
    val drafts: kotlin.collections.Map<kotlin.String, ListConfigsResponseDataInnerDraftsValue>,

    /* Per-env latest published values (only returned by `GET /{id}`, not list). */
    @Json(name = "values")
    val propertyValues: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Per-env draft values (only returned by `GET /{id}`). */
    @Json(name = "draftValues")
    val draftValues: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

