/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Desired direction of movement. `higher_better` (default), `lower_better`, or `neutral` (guardrail).
 *
 * Values: higher_better,lower_better,neutral
 */

@JsonClass(generateAdapter = false)
enum class MetricDirection(val value: kotlin.String) {

    @Json(name = "higher_better")
    higher_better("higher_better"),

    @Json(name = "lower_better")
    lower_better("lower_better"),

    @Json(name = "neutral")
    neutral("neutral");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MetricDirection) "$data" else null

        /**
         * Returns a valid [MetricDirection] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MetricDirection? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

