/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.MeasurePlanResource
import ai.shipeasy.admin.models.MeasurePlanStep

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An assistant-proposed measurement plan: what it already built, what it still needs, and the event instrumentation you implement.
 *
 * @param created Resources the assistant already created on approval (live now) — don't recreate them.
 * @param instrumentation The code instrumentation to implement before the metrics can collect data.
 * @param goal The customer's underlying intent in their own words — WHAT they want to learn or achieve and WHY, independent of the specific steps. The plan below is a best-effort proposal made without repo access; when the code reveals a better path, this goal is the target you optimize for, not literal step-adherence.
 * @param pending Resources the assistant couldn't create yet (usually a metric whose backing event isn't emitted); create these after the instrumentation lands.
 */


data class OpsMeasurePlanContext (

    /* Resources the assistant already created on approval (live now) — don't recreate them. */
    @Json(name = "created")
    val created: kotlin.collections.List<MeasurePlanResource>,

    /* The code instrumentation to implement before the metrics can collect data. */
    @Json(name = "instrumentation")
    val instrumentation: kotlin.collections.List<MeasurePlanStep>,

    /* The customer's underlying intent in their own words — WHAT they want to learn or achieve and WHY, independent of the specific steps. The plan below is a best-effort proposal made without repo access; when the code reveals a better path, this goal is the target you optimize for, not literal step-adherence. */
    @Json(name = "goal")
    val goal: kotlin.String? = null,

    /* Resources the assistant couldn't create yet (usually a metric whose backing event isn't emitted); create these after the instrumentation lands. */
    @Json(name = "pending")
    val pending: kotlin.collections.List<MeasurePlanResource>? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

