/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Optional group-by clause (ignored for experiment analysis).
 *
 * @param op `by` keeps the listed labels; `without` drops them.
 * @param labels Labels to group by (max 5).
 */


data class QueryIrGroupBy (

    /* `by` keeps the listed labels; `without` drops them. */
    @Json(name = "op")
    val op: QueryIrGroupBy.Op,

    /* Labels to group by (max 5). */
    @Json(name = "labels")
    val labels: kotlin.collections.List<kotlin.String>

) {

    /**
     * `by` keeps the listed labels; `without` drops them.
     *
     * Values: by,without
     */
    @JsonClass(generateAdapter = false)
    enum class Op(val value: kotlin.String) {
        @Json(name = "by") by("by"),
        @Json(name = "without") without("without");
    }

}

