/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.QueryIrAggOneOf9NumeratorFiltersInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Numerator or denominator arm of a `ratio` aggregation.
 *
 * @param agg Counting mode for this ratio arm.
 * @param metric Source event name for this ratio arm.
 * @param filters Optional label filters.
 */


data class QueryIrAggOneOf9Numerator (

    /* Counting mode for this ratio arm. */
    @Json(name = "agg")
    val agg: QueryIrAggOneOf9Numerator.Agg,

    /* Source event name for this ratio arm. */
    @Json(name = "metric")
    val metric: kotlin.String,

    /* Optional label filters. */
    @Json(name = "filters")
    val filters: kotlin.collections.List<QueryIrAggOneOf9NumeratorFiltersInner>? = null

) {

    /**
     * Counting mode for this ratio arm.
     *
     * Values: count_users,count_events
     */
    @JsonClass(generateAdapter = false)
    enum class Agg(val value: kotlin.String) {
        @Json(name = "count_users") count_users("count_users"),
        @Json(name = "count_events") count_events("count_events");
    }

}

