/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param n Retention window in days (1–90).
 */


data class QueryIrAggOneOf8 (

    @Json(name = "kind")
    val kind: QueryIrAggOneOf8.Kind,

    /* Retention window in days (1–90). */
    @Json(name = "n")
    val n: kotlin.Int

) {

    /**
     * 
     *
     * Values: retention_Nd
     */
    @JsonClass(generateAdapter = false)
    enum class Kind(val value: kotlin.String) {
        @Json(name = "retention_Nd") retention_Nd("retention_Nd");
    }

}

