/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.SetExperimentMetricsRequestMetricsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/experiments/{id}/metrics`. Replaces the experiment's metric attachments wholesale. Returns `422` if any `metric_id` is unknown.
 *
 * @param metrics Replacement metrics list — replaces the current attachments wholesale.
 */


data class SetExperimentMetricsRequest (

    /* Replacement metrics list — replaces the current attachments wholesale. */
    @Json(name = "metrics")
    val metrics: kotlin.collections.List<SetExperimentMetricsRequestMetricsInner>

) {


}

