/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param metricId 
 * @param role 
 * @param minEffectOfInterest The resolved per-experiment override, or `null` when this attachment inherits the metric's `default_min_effect_of_interest`.
 */


data class SetExperimentMetricsResponseMetricsInner (

    @Json(name = "metric_id")
    val metricId: kotlin.String,

    @Json(name = "role")
    val role: SetExperimentMetricsResponseMetricsInner.Role,

    /* The resolved per-experiment override, or `null` when this attachment inherits the metric's `default_min_effect_of_interest`. */
    @Json(name = "min_effect_of_interest")
    val minEffectOfInterest: java.math.BigDecimal?

) {

    /**
     * 
     *
     * Values: goal,guardrail,secondary
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "goal") goal("goal"),
        @Json(name = "guardrail") guardrail("guardrail"),
        @Json(name = "secondary") secondary("secondary");
    }

}

