/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /api/admin/i18n/set`. Upserts one key's value and publishes the profile live.
 *
 * @param key Dotted key path to set, e.g. `home.cta`.
 * @param `value` New value for the key. Inserted when the key is new, overwritten when it exists.
 * @param profile Profile name to target, e.g. `en:prod`. Omit to target the project's default-marked profile.
 * @param description Optional human note to store with the key.
 */


data class SetI18nLabelRequest (

    /* Dotted key path to set, e.g. `home.cta`. */
    @Json(name = "key")
    val key: kotlin.String,

    /* New value for the key. Inserted when the key is new, overwritten when it exists. */
    @Json(name = "value")
    val `value`: kotlin.String,

    /* Profile name to target, e.g. `en:prod`. Omit to target the project's default-marked profile. */
    @Json(name = "profile")
    val profile: kotlin.String? = null,

    /* Optional human note to store with the key. */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

