/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The Slack message the driver posted for this item.
 *
 * @param channel Slack channel id the message was posted to.
 * @param ts Slack message timestamp (`ts`) — the message handle used for in-place `chat.update`.
 * @param postedAt ISO-8601 timestamp the message was posted.
 */


data class SlackConnectorDataMessage (

    /* Slack channel id the message was posted to. */
    @Json(name = "channel")
    val channel: kotlin.String,

    /* Slack message timestamp (`ts`) — the message handle used for in-place `chat.update`. */
    @Json(name = "ts")
    val ts: kotlin.String,

    /* ISO-8601 timestamp the message was posted. */
    @Json(name = "postedAt")
    val postedAt: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

