/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.SlackConnectorDataMessage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Slack connector trace — the message the driver posted for this item. The linked pull request is recorded on `github.pr`, not here.
 *
 * @param message 
 */


data class SlackConnectorData (

    @Json(name = "message")
    val message: SlackConnectorDataMessage? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

