/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.JulesTriggerConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Per-provider PATCH body for editing an existing `jules_trigger` connector. `config` replaces the stored config wholesale; `name` and either credential are optional.
 *
 * @param provider Discriminator. Google Jules trigger.
 * @param config 
 * @param name New connector label. Optional — omit to leave it unchanged.
 * @param apiKey New Jules launch key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `opsKey`. Encrypted; never returned.
 * @param opsKey New restricted Shipeasy ops key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `apiKey`. Encrypted; never returned.
 */


data class UpdateJulesTriggerRequest (

    /* Discriminator. Google Jules trigger. */
    @Json(name = "provider")
    val provider: UpdateJulesTriggerRequest.Provider,

    @Json(name = "config")
    val config: JulesTriggerConfig,

    /* New connector label. Optional — omit to leave it unchanged. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* New Jules launch key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `opsKey`. Encrypted; never returned. */
    @Json(name = "apiKey")
    val apiKey: kotlin.String? = null,

    /* New restricted Shipeasy ops key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `apiKey`. Encrypted; never returned. */
    @Json(name = "opsKey")
    val opsKey: kotlin.String? = null

) {

    /**
     * Discriminator. Google Jules trigger.
     *
     * Values: jules_trigger
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "jules_trigger") jules_trigger("jules_trigger");
    }

}

