/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.JulesTriggerConfig
import ai.shipeasy.admin.models.UpdateClaudeTriggerRequest
import ai.shipeasy.admin.models.UpdateCopilotTriggerRequest
import ai.shipeasy.admin.models.UpdateCursorTriggerRequest
import ai.shipeasy.admin.models.UpdateJulesTriggerRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `PATCH /api/admin/connectors/{id}/trigger`, discriminated on `provider`. Edits an existing trigger connector: the non-secret `config` is always supplied and replaces the stored config wholesale; `name` and the credential secret(s) are optional (a supplied secret rotates just that key, a blank/omitted one leaves the stored cipher untouched).
 *
 * @param provider Discriminator. Google Jules trigger.
 * @param config 
 * @param name New connector label. Optional — omit to leave it unchanged.
 * @param token New Copilot-licensed user PAT (secret). Optional — omit to leave the stored cipher untouched. Encrypted; never returned.
 * @param apiKey New Jules launch key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `opsKey`. Encrypted; never returned.
 * @param opsKey New restricted Shipeasy ops key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `apiKey`. Encrypted; never returned.
 */


interface UpdateTriggerConnectorRequest {

    /* Discriminator. Google Jules trigger. */
    @Json(name = "provider")
    val provider: UpdateTriggerConnectorRequest.Provider
    @Json(name = "config")
    val config: JulesTriggerConfig
    /* New connector label. Optional — omit to leave it unchanged. */
    @Json(name = "name")
    val name: kotlin.String?
    /* New Copilot-licensed user PAT (secret). Optional — omit to leave the stored cipher untouched. Encrypted; never returned. */
    @Json(name = "token")
    val token: kotlin.String?
    /* New Jules launch key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `opsKey`. Encrypted; never returned. */
    @Json(name = "apiKey")
    val apiKey: kotlin.String?
    /* New restricted Shipeasy ops key (secret). Optional — omit to leave the stored key untouched. Rotatable independently of `apiKey`. Encrypted; never returned. */
    @Json(name = "opsKey")
    val opsKey: kotlin.String?
    /**
     * Discriminator. Google Jules trigger.
     *
     * Values: jules_trigger
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "jules_trigger") jules_trigger("jules_trigger");
    }

}

