/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.OpsItemNotifyOrNull
import ai.shipeasy.admin.models.OpsItemPriorityOrNull
import ai.shipeasy.admin.models.OpsItemStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Content + triage update for a `bug` item (`PATCH /api/admin/ops/{handle}` when the item is a bug).
 *
 * @param title New bug title (no leading/trailing whitespace).
 * @param stepsToReproduce Updated reproduction steps.
 * @param actualResult Updated actual result.
 * @param expectedResult Updated expected result.
 * @param status 
 * @param priority 
 * @param githubPrNumber Link (or, when `null`, unlink) a GitHub pull request to this bug.
 * @param notify 
 */


data class UpdateBugRequest (

    /* New bug title (no leading/trailing whitespace). */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Updated reproduction steps. */
    @Json(name = "stepsToReproduce")
    val stepsToReproduce: kotlin.String? = null,

    /* Updated actual result. */
    @Json(name = "actualResult")
    val actualResult: kotlin.String? = null,

    /* Updated expected result. */
    @Json(name = "expectedResult")
    val expectedResult: kotlin.String? = null,

    @Json(name = "status")
    val status: OpsItemStatus? = null,

    @Json(name = "priority")
    val priority: OpsItemPriorityOrNull? = null,

    /* Link (or, when `null`, unlink) a GitHub pull request to this bug. */
    @Json(name = "githubPrNumber")
    val githubPrNumber: kotlin.Int? = null,

    @Json(name = "notify")
    val notify: OpsItemNotifyOrNull? = null

) {


}

