/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `PATCH /api/admin/configs/{id}`. Partial — only supplied fields change. `value` republishes on every env.
 *
 * @param schema Replacement schema. When supplied, the new schema is validated against every published value before it lands.
 * @param `value` 
 * @param folder Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
 */


data class UpdateConfigRequest (

    /* Replacement schema. When supplied, the new schema is validated against every published value before it lands. */
    @Json(name = "schema")
    val schema: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "value")
    val `value`: kotlin.Any? = null,

    /* Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`). */
    @Json(name = "folder")
    val folder: kotlin.String? = null

) {


}

