/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `PUT /api/admin/i18n/keys/{id}`. Updates one existing key's value.
 *
 * @param `value` New value for the key (the only overwrite path).
 * @param description Optional human note to store with the key.
 * @param variables Explicit `{{var}}` placeholder names in the value. Omit to auto-derive them from the value.
 */


data class UpdateI18nKeyRequest (

    /* New value for the key (the only overwrite path). */
    @Json(name = "value")
    val `value`: kotlin.String,

    /* Optional human note to store with the key. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Explicit `{{var}}` placeholder names in the value. Omit to auto-derive them from the value. */
    @Json(name = "variables")
    val variables: kotlin.collections.List<kotlin.String>? = null

) {


}

