/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.shipeasy.admin.models

import ai.shipeasy.admin.models.ClaudeTriggerConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Per-provider PATCH body for editing an existing `claude_trigger` connector (the dashboard \"Triggers\" tab). The non-secret `config` is always supplied and replaces the stored config wholesale; `name` and `token` are optional.
 *
 * @param provider Discriminator. Claude Code scheduled-routine trigger.
 * @param config 
 * @param name New connector label. Optional — omit to leave it unchanged.
 * @param token New fire bearer token (secret). Optional — a blank/omitted token leaves the stored cipher untouched; a supplied one replaces it. Encrypted; never returned.
 */


data class UpdateClaudeTriggerRequest (

    /* Discriminator. Claude Code scheduled-routine trigger. */
    @Json(name = "provider")
    val provider: UpdateClaudeTriggerRequest.Provider,

    @Json(name = "config")
    val config: ClaudeTriggerConfig,

    /* New connector label. Optional — omit to leave it unchanged. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* New fire bearer token (secret). Optional — a blank/omitted token leaves the stored cipher untouched; a supplied one replaces it. Encrypted; never returned. */
    @Json(name = "token")
    val token: kotlin.String? = null

) {

    /**
     * Discriminator. Claude Code scheduled-routine trigger.
     *
     * Values: claude_trigger
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "claude_trigger") claude_trigger("claude_trigger");
    }

}

