// Generate README.md from the docs in docs/ and keep the embedded agent skill
// (src/main/resources/shipeasy-skill/SKILL.md) in sync with docs/skill/SKILL.md.
//
//     java tools/GenReadme.java
//
// A JDK-only single-file program (Java 11+ source launch — no build, no deps).
// CI (.github/workflows/tests.yml) re-runs it and `git diff --exit-code`s the
// result to catch drift. Idempotent. Run from the repo root (CWD).
import java.io.IOException;
import java.nio.file.*;
import java.util.*;
import java.util.regex.*;

public class GenReadme {
    static final String OWNER = "shipeasy-ai";
    static final String REPO = "sdk-kotlin";
    static final String SDK = "kotlin";
    static final String ARTIFACT = "shipeasy-kotlin";
    static final String BLOB = "https://github.com/" + OWNER + "/" + REPO + "/blob/main";
    static final String PAGES = "https://" + OWNER + ".github.io/" + REPO;

    static final String[] PAGE_ORDER = {
        "overview", "installation", "configuration", "flags", "configs",
        "killswitches", "experiments", "i18n", "error-reporting", "testing",
        "openfeature", "advanced"
    };
    static final Map<String, String> TITLE = new LinkedHashMap<>();
    static final Map<String, String> BLURB = new LinkedHashMap<>();
    static {
        TITLE.put("overview", "Overview"); TITLE.put("installation", "Installation");
        TITLE.put("configuration", "Configuration"); TITLE.put("flags", "Feature flags");
        TITLE.put("configs", "Dynamic configs"); TITLE.put("killswitches", "Kill switches");
        TITLE.put("experiments", "Experiments"); TITLE.put("i18n", "Internationalization");
        TITLE.put("error-reporting", "Error reporting"); TITLE.put("testing", "Testing");
        TITLE.put("openfeature", "OpenFeature"); TITLE.put("advanced", "Advanced");
        BLURB.put("overview", "The `configure()` + `Client(user)` model.");
        BLURB.put("installation", "Install (Gradle/Maven), Ktor / Spring, `configure()` wiring.");
        BLURB.put("configuration", "Keys, `attributes`, one-shot vs poll, every option.");
        BLURB.put("flags", "`getFlag`, `getFlagDetail`, defaults.");
        BLURB.put("configs", "`getConfig`, typed reads, defaults.");
        BLURB.put("killswitches", "`getKillswitch`, named switches.");
        BLURB.put("experiments", "`universe(name).assign()`, `Assignment`, `track`.");
        BLURB.put("i18n", "SSR bootstrap + i18n loader tags.");
        BLURB.put("error-reporting", "`see()` structured error reporting.");
        BLURB.put("testing", "`configureForTesting` / `configureForOffline`, overrides.");
        BLURB.put("openfeature", "OpenFeature interop notes.");
        BLURB.put("advanced", "Anon-id filter, private attributes, sticky bucketing, SSR.");
    }

    public static void main(String[] args) throws IOException {
        Path root = Paths.get("").toAbsolutePath();
        Path docs = root.resolve("docs");

        String install = firstCode(read(docs, "pages/installation.md"), "kotlin");
        if (install.isEmpty()) install = firstCode(read(docs, "pages/installation.md"), "groovy");
        String quickstart = firstCode(read(docs, "pages/overview.md"), "kotlin");
        String testingMd = read(docs, "pages/testing.md");
        String testingLead = absolutize(leadParagraph(testingMd));
        String testingCode = firstCode(testingMd, "kotlin");

        StringBuilder rows = new StringBuilder();
        for (String key : PAGE_ORDER) {
            String blurb = BLURB.getOrDefault(key, "");
            if (blurb.length() > 90) blurb = blurb.substring(0, 87).trim() + "…";
            rows.append("| [").append(TITLE.get(key)).append("](").append(BLOB)
                .append("/docs/pages/").append(key).append(".md) | ").append(blurb).append(" |\n");
        }

        String readme = ""
            + "<!--\n"
            + "  This file is GENERATED by tools/GenReadme.java from docs/.\n"
            + "  Do NOT edit by hand — edit the docs, then run: java tools/GenReadme.java\n"
            + "-->\n\n"
            + "# shipeasy-kotlin\n\n"
            + "[![Tests](https://github.com/" + OWNER + "/" + REPO + "/actions/workflows/tests.yml/badge.svg)](https://github.com/" + OWNER + "/" + REPO + "/actions/workflows/tests.yml)\n"
            + "[![Maven Central](https://img.shields.io/maven-central/v/ai.shipeasy/" + ARTIFACT + ".svg)](https://central.sonatype.com/artifact/ai.shipeasy/" + ARTIFACT + ")\n"
            + "[![Kotlin](https://img.shields.io/badge/Kotlin-1.9%2B-purple.svg)](https://kotlinlang.org)\n\n"
            + "Server SDK for [Shipeasy](https://shipeasy.ai) — **feature flags, dynamic\n"
            + "configs, kill switches, A/B experiments, and metric tracking** for Kotlin/JVM.\n"
            + "Server-key only; never embed in a client app.\n\n"
            + "> 📚 **Full documentation:** **<" + PAGES + "/>** — also browsable under\n"
            + "> [`docs/`](" + BLOB + "/docs). This README is generated from those docs.\n\n"
            + "## 🤖 Using an AI agent?\n\n"
            + "This SDK ships an installable **agent skill** — a copy-paste-ready guide to\n"
            + "`configure()` + `Client(user)`, testing, experiments, error reporting, and more,\n"
            + "with links the agent can pull for deeper docs:\n\n"
            + "- **Skill:** [`docs/skill/SKILL.md`](" + BLOB + "/docs/skill/SKILL.md) · raw:\n"
            + "  `" + PAGES + "/skill/SKILL.md`\n"
            + "- **Install it** (bundled in the jar — no network):\n"
            + "  `java -cp " + ARTIFACT + ".jar ai.shipeasy.SkillInstallerKt install` → `.claude/skills/shipeasy-" + SDK + "/SKILL.md`\n"
            + "  (or via the Shipeasy CLI: `shipeasy docs skill --sdk " + SDK + " --install`)\n\n"
            + "**Humans:** you can copy that skill straight into your own project's agent skills\n"
            + "directory so your coding agent always uses the correct Shipeasy patterns. Every\n"
            + "doc page and snippet is also fetchable by URL — start from the manifest at\n"
            + "`" + PAGES + "/manifest.json`.\n\n"
            + "## Install\n\n"
            + "```kotlin\n" + install + "\n```\n\n"
            + "Per-framework setup (Ktor / Spring) is on the\n"
            + "[Installation](" + BLOB + "/docs/pages/installation.md) page.\n\n"
            + "## Quickstart — `configure()` once, then `Client(user)` per request\n\n"
            + "```kotlin\n" + quickstart + "\n```\n\n"
            + "Constructing `Client(user)` before `configure()` throws.\n\n"
            + "## Documentation\n\n"
            + "| Page | What |\n| --- | --- |\n" + rows
            + "\nCopy-paste snippets live under [`docs/snippets/`](" + BLOB + "/docs/snippets)\n"
            + "(release · metrics · i18n · ops); an installable agent skill is at\n"
            + "[`docs/skill/SKILL.md`](" + BLOB + "/docs/skill/SKILL.md).\n\n"
            + "## Testing\n\n" + testingLead + "\n\n"
            + "```kotlin\n" + testingCode + "\n```\n\n"
            + "More — the on-the-spot override helpers and a working example snapshot file — on\n"
            + "the [Testing](" + BLOB + "/docs/pages/testing.md) page.\n\n"
            + "## License\n\n"
            + "See [LICENSE](" + BLOB + "/LICENSE). Evaluation is tested against the cross-language\n"
            + "MurmurHash3 vectors in `experiment-platform/04-evaluation.md`.\n";

        Files.writeString(root.resolve("README.md"), readme);

        Path skillSrc = docs.resolve("skill/SKILL.md");
        Path skillDst = root.resolve("src/main/resources/shipeasy-skill/SKILL.md");
        Files.createDirectories(skillDst.getParent());
        Files.copy(skillSrc, skillDst, StandardCopyOption.REPLACE_EXISTING);

        System.out.println("Wrote README.md (" + readme.length() + " chars) + synced "
            + "src/main/resources/shipeasy-skill/SKILL.md from " + PAGE_ORDER.length + " doc pages.");
    }

    static String read(Path docs, String rel) throws IOException { return Files.readString(docs.resolve(rel)); }

    static String firstCode(String md, String lang) {
        Matcher m = Pattern.compile("```" + Pattern.quote(lang) + "\\n(.*?)```", Pattern.DOTALL).matcher(md);
        return m.find() ? m.group(1).stripTrailing() : "";
    }

    static String leadParagraph(String md) {
        List<String> out = new ArrayList<>();
        boolean started = false;
        for (String line : md.split("\n", -1)) {
            if (!started) { started = line.startsWith("# "); continue; }
            String s = line.strip();
            if (s.isEmpty()) { if (!out.isEmpty()) break; else continue; }
            if (!s.isEmpty() && "#`>|-<".indexOf(s.charAt(0)) >= 0) { if (!out.isEmpty()) break; else continue; }
            out.add(s);
        }
        return String.join(" ", out).replaceAll("\\s+", " ").strip();
    }

    static String absolutize(String text) {
        Matcher m = Pattern.compile("\\]\\(([\\w./-]+?\\.md)(#[\\w-]+)?\\)").matcher(text);
        StringBuilder sb = new StringBuilder();
        while (m.find()) {
            String path = m.group(1);
            String frag = m.group(2) == null ? "" : m.group(2);
            String repl = path.startsWith("/") ? m.group(0) : "](" + BLOB + "/docs/pages/" + path + frag + ")";
            m.appendReplacement(sb, Matcher.quoteReplacement(repl));
        }
        m.appendTail(sb);
        return sb.toString();
    }
}
